packages:
  - "."

overrides:
  "tailwindcss>nanoid": "3.3.7"
  "ics>nanoid": "3.3.18"
  "path-to-regexp": "0.1.13"
  "lodash": "4.18.0"
  "lodash-es": "4.18.0"

patchedDependencies:
  "wouter@3.7.1": "patches/wouter@3.7.1.patch"
