import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "de" | "en";

const translations = {
  de: {
    // Navigation & Layout
    nav: {
      home: "Startseite",
      examiners: "Prüfer:innen",
      login: "Anmelden",
      logout: "Abmelden",
      dashboard: "Dashboard",
      student: "Studierende:r",
      examiner: "Prüfer:in",
      admin: "Verwaltung",
      directory: "Prüfer:innen-Verzeichnis",
      myProfile: "Mein Profil",
      changePassword: "Passwort ändern",
      notifications: "Benachrichtigungen",
      noNotifications: "Keine Benachrichtigungen",
      markAllRead: "Alle als gelesen markieren",
      openNav: "Navigation öffnen",
      loading: "Lade...",
    },
    // Landing Page
    landing: {
      title: "Thesis Match Maker",
      subtitle: "Finden Sie Ihre 2 Betreuungspersonen für Ihre Abschlussarbeit",
      tagline: "Die Plattform der HTW Berlin zur Vermittlung von Abschlussarbeiten",
      loginBtn: "Jetzt anmelden",
      loginMagicLink: "Anmelden via Magic Link",
      loginManus: "Anmelden via HTW-Konto",
      emailPlaceholder: "Ihre HTW-E-Mail-Adresse",
      sendLink: "Magic Link senden",
      sending: "Wird gesendet…",
      linkSent: "Magic Link gesendet! Bitte prüfen Sie Ihr E-Mail-Postfach.",
      browseExaminers: "Prüfer:innen-Verzeichnis",
      openArea: "Bereich öffnen",
      fachbereich: "Fachbereich 3",
      heroDesc: "Die zentrale Plattform der HTW Berlin für das Matchmaking zwischen Studierenden und Prüfer:innen – von der ersten Betreuungsanfrage bis zum Kolloquium.",
      startAsStudent: "Als Studierende:r starten",
      examinerArea: "Prüfer:innen-Bereich",
      features: {
        match: "Betreuer:innen finden",
        matchDesc: "Finden Sie passende Erst- und Zweitprüfer:innen für Ihre Abschlussarbeit.",
        track: "Status verfolgen",
        trackDesc: "Behalten Sie den Überblick über Anfragen, Deadlines und das Kolloquium.",
        secure: "Sicher & Datenschutzkonform",
        secureDesc: "Alle Daten werden gemäß DSGVO verarbeitet und sicher gespeichert.",
      },
      roles: {
        title: "Für wen ist die Plattform?",
        subtitle: "Drei Rollen – eine Plattform",
        student: "Studierende:r",
        studentFeatures: ["Thema einreichen", "Prüfer:innen anfragen", "Status verfolgen", "Kolloquium planen"],
        examiner: "Prüfer:in",
        examinerFeatures: ["Anfragen verwalten", "Kapazität pflegen", "Gutachten-Vorlagen", "Kolloquiums-Kalender"],
        admin: "Verwaltung",
        adminFeatures: ["Zulassungs-Workflow", "Akte X", "Audit-Log"],
      },
      process: {
        label: "Der Ablauf",
        title: "Von der Idee bis zur Urkunde",
        steps: [
          { number: "01", title: "Matchmaking", description: "Thema einreichen und passende Prüfer:innen kontaktieren." },
          { number: "02", title: "Zulassung", description: "Verwaltung prüft Voraussetzungen und erteilt offizielle Zulassung." },
          { number: "03", title: "Abgabe", description: "Upload der Arbeit bis 23:59 des Abgabetermins mit Opt-ins." },
          { number: "04", title: "Gutachtenphase", description: "Erst- und Zweitprüfer:in verfassen unabhängig ihre Gutachten." },
          { number: "05", title: "Kolloquium", description: "Terminfindung, Raumbuchung und Einladung mit Kalender-Anhang." },
          { number: "06", title: "Abschluss", description: "Protokoll, Notenblatt und Urkunde mit digitaler Signatur." },
        ],
      },
      tech: {
        label: "Technischer Rahmen",
        title: "Selbstgehostet. Souverän. Sicher.",
        desc: "Die Plattform läuft vollständig unter",
        descSuffix: "– ohne externe Authentifizierungs-Dienste oder US-Cloud-Anbieter.",
        items: [
          { title: "On-Premise Hosting", desc: "Vollständige Datenhoheit, keine externen Zwischenebenen.", icon: "🏗️" },
          { title: "SMTP-Authentifizierung", desc: "Login und Benachrichtigungen direkt über den HTW-Mailserver.", icon: "✉️" },
          { title: "DSGVO-konform", desc: "Studentische Telefonnummern bleiben für Kommilitonen unsichtbar.", icon: "🔒" },
          { title: "JWT-gesicherte CTAs", desc: "Prüfer:innen können Anfragen per E-Mail-Link ohne Login beantworten.", icon: "🔑" },
        ],
      },
      footer: {
        forStudents: "Für Studierende",
        forExaminers: "Für Prüfer:innen",
        contact: "Kontakt",
        aboutMe: "Über mich",
        studentLinks: ["Prüfer:innen finden", "Thema einreichen", "Abgabeportal", "Kolloquium planen", "FAQ & Leitfaden"],
        examinerLinks: ["Anfragen verwalten", "Verfügbarkeit pflegen", "Gutachten-Vorlagen", "LVVO-Export", "Kommissions-Tools"],
        imprint: "Impressum",
        privacy: "Datenschutz",
        accessibility: "Barrierefreiheit",
        copyright: "© 2026 HTW Berlin",
      },
    },
    // Student Dashboard
    student: {
      title: "Studierenden-Dashboard",
      newRequest: "Neue Anfrage",
      myRequests: "Meine Anfragen",
      noRequests: "Noch keine Anfragen eingereicht.",
      submitRequest: "Anfrage einreichen",
      thesisTitle: "Titel der Abschlussarbeit",
      description: "Beschreibung",
      department: "Fachbereich",
      degreeType: "Abschlussart",
      targetSemester: "Zielsemester",
      language: "Sprache",
      uploadExpose: "Exposé hochladen (PDF)",
      uploading: "Wird hochgeladen…",
      uploadSuccess: "Exposé erfolgreich hochgeladen!",
      deadline: "Abgabefrist",
      downloadIcs: "Termin herunterladen (.ics)",
      colloquiums: "Kolloquium",
      history: "Verlauf",
      // Request-Formular
      draftRestore: "Sie haben einen unvollständigen Entwurf. Möchten Sie ihn wiederherstellen?",
      draftRestoreBtn: "Wiederherstellen",
      draftDiscardBtn: "Verwerfen",
      topicQuestion: "Wie möchten Sie Ihr Thema erhalten?",
      ownTopic: "Ich habe einen eigenen Vorschlag",
      ownTopicDesc: "Sie bringen ein konkretes Thema mit. Titel, Beschreibung und Expoé werden abgefragt.",
      assignedTopic: "Ich möchte ein Thema zugeteilt bekommen",
      assignedTopicDesc: "Die Prüfer:in schlägt ein passendes Thema vor. Nur Pflichtfelder werden abgefragt.",
      exposeHint: "Das Expoé ist ein ca. 2-seitiges Dokument, das Ihr Thema, die Problemstellung und den geplanten Ansatz kurz zusammenfasst. Es ist keine Pflichtangabe, erhöht aber Ihre Chancen auf eine Zusage.",
      pdfSelect: "PDF auswählen...",
      pleaseSelectSemester: "Bitte wählen Sie ein Zielsemester aus.",
      pleaseSelectExaminer: "Bitte wählen Sie eine Wunschgutachter:in aus.",
      pleaseSelect: "-- Bitte wählen --",
      noProgForSelection: "Keine Studiengang für diese Auswahl verfügbar",
      degreeFromProfile: "Abschlussart aus Ihrem Profil übernommen – nicht änderbar.",
      semesterFromProfile: "Automatisch aus Ihrem Profil übernommen – nicht änderbar.",
      profileDataLabel: "Profildaten (nicht änderbar)",
      profileDataHint: "Fachbereich, Studiengang und Abschlussart werden aus Ihrem Profil übernommen und können hier nicht geändert werden.",
      noProgrammeTitle: "Kein Studiengang im Profil hinterlegt",
      noProgrammeDesc: "Bitte legen Sie zunächst Ihren Studiengang in Ihrem Profil fest, bevor Sie eine Anfrage einreichen.",
      firstExaminer: "Erstgutachter:in auswählen",
      firstExaminerDesc: "Wählen Sie Ihre Wunsch-Erstgutachter:in. Diese Person wird per E-Mail kontaktiert und muss zustimmen.",
      secondExaminerNote: "Die Auswahl der Zweitgutachter:in ist erst möglich, nachdem die Erstgutachter:in zugesagt hat.",
      noPreference: "Keine Präferenz – Zweitgutachter:in kann zugeteilt werden",
      availableAfterFirst: "Verfügbar nach Erstgutachter-Zusage",
      selectSecondExaminer: "Zweitgutachter:in auswählen",
      secondExaminerAvailable: "Sie können jetzt Ihre Präferenz für die Zweitgutachter:in angeben.",
      secondPrefSaved: "Zweitgutachter:in-Präferenz gespeichert.",
      noExaminersFound: "Keine Prüfer:innen gefunden.",
      searchExaminer: "Prüfer:in suchen...",
      nextSteps: "Nächste Schritte",
      nextStepsDesc: "Reiche deine Themenidee ein und finde passende Prüfer:innen für deine Abschlussarbeit. Das System benachrichtigt dich per E-Mail über alle Statusänderungen.",
      addToCalendar: "Zum Kalender hinzufügen (.ics)",
      auditStatusChanged: "Status geändert",
      auditExaminerAccepted: "Prüfer:in hat angenommen",
      auditExaminerRejected: "Prüfer:in hat abgelehnt",
      auditFirstAssigned: "Erstprüfer:in zugewiesen",
      auditSecondAssigned: "Zweitprüfer:in zugewiesen",
      selectRequest: "Anfrage auswählen",
      noHistory: "Noch keine Einträge.",
      reason: "Begründung",
      findExaminers: "Prüfer:innen finden",
      submitIdea: "Themenidee einreichen",
      submitIdeaDesc: "Beschreibe deine Themenidee. Admins und Prüfer:innen werden benachrichtigt.",
      browseExaminers: "Verfügbare Prüfer:innen",
      browseExaminersDesc: "Durchsuche Profile und finde passende Betreuer:innen für deine Arbeit.",
      fileTooLarge: "Die Datei ist zu groß. Bitte laden Sie eine PDF-Datei mit maximal 5 MB hoch.",
      submitting: "Wird eingereicht...",
      requestSubmitted: "Anfrage erfolgreich eingereicht!",
      validationTitle: "Bitte geben Sie einen Titel ein.",
      validationTitleShort: "Der Titel sollte mindestens 10 Zeichen lang sein.",
      validationDesc: "Bitte beschreiben Sie Ihr Thema.",
      validationDescShort: "Die Beschreibung sollte mindestens 30 Zeichen lang sein.",
      validationSemester: "Bitte wählen Sie ein Zielsemester aus.",
      validationExaminer: "Bitte wählen Sie eine Wunschgutachter:in aus.",
      validationFix: "Bitte korrigieren Sie die markierten Felder.",
      uploadFailed: "Exposé-Upload fehlgeschlagen",
      previewTitle: "Vorschau Ihrer Anfrage",
      previewSubtitle: "Bitte überprüfen Sie Ihre Angaben vor dem endgültigen Einreichen.",
      editBack: "Zurück bearbeiten",
      topicSelection: "Themenauswahl",
      ownTopicLabel: "Eigener Vorschlag",
      assignedTopicLabel: "Themenzuteilung gewünscht",
      topicSection: "Thema",
      abstractLabel: "Abstract",
      exposeLabel: "Exposé",
      conditionsSection: "Rahmenbedingungen",
      departmentField: "Fachbereich / Studiengang",
      targetSemesterField: "Zielsemester",
      preferredExaminer: "Wunschgutachter:in",
      degreeField: "Abschlussart",
      languageField: "Sprache",
      notSpecified: "Nicht angegeben",
      notSelected: "Nicht ausgewählt",
      editBtn: "Bearbeiten",
      printBtn: "Als PDF speichern / Drucken",
      submitNow: "Jetzt einreichen",
      previewSubmit: "Vorschau & Einreichen",
      printHeader: "Betreuungsanfrage – Zusammenfassung",
      degreeSection: "Abschlussart",
      fachbereichLabel: "Fachbereich",
      studyProgramLabel: "Studiengang",
      semesterLabel: "Geplantes Semester der Thesis",
      thesisLanguageLabel: "Sprache der Thesis",
      thesisLangDe: "Deutsch",
      thesisLangEn: "Englisch",
      firstExaminerLabel: "Erstgutachter:in",
      capacityFull: "Ausgelastet",
      capacityAlmost: "Fast ausgelastet",
      exposeView: "Exposé ansehen",
      exposeReplace: "Ersetzen",
      exposeUploadBtn: "Exposé hochladen",
      exposeUploadSuccess: "Exposé erfolgreich hochgeladen!",
      exposeUploadFailed: "Upload fehlgeschlagen",
      exposeFileTooLarge: "Datei ist zu groß (max. 16 MB).",
      exposePdfOnly: "Nur PDF-Dateien sind erlaubt.",
      secondExaminerTitle: "Zweitgutachter:in auswählen",
      firstExaminerAccepted: "Erstgutachter:in hat zugesagt",
      currentPref: "Aktuelle Präferenz",
      save: "Speichern",
      noRequestsTitle: "Noch keine Anfragen",
      noRequestsDesc: "Reiche deine erste Themenidee ein, um loszulegen.",
      colStatusScheduled: "Geplant",
      colStatusCompleted: "Abgeschlossen",
      colStatusCancelled: "Abgesagt",
      historyTitle: "Verlauf",
      historySelectRequest: "Anfrage auswählen",
      historyPlease: "-- Bitte wählen --",
      historyNoEntries: "Noch keine Einträge.",
      historyReason: "Begründung",
      auditThesisCreated: "Anfrage eingereicht",
      auditColloquiumCreated: "Kolloquium angelegt",
      auditDeadlineSet: "Abgabefrist gesetzt",
      tabRequests: "Meine Anfragen",
      tabNew: "Neue Anfrage einreichen",
      tabExaminers: "Prüfer:innen finden",
      tabColloquiums: "Mein Kolloquium",
      tabHistory: "Statushistorie",
      myColloquium: "Mein Kolloquium",
      noColloquiums: "Noch kein Kolloquium geplant.",
      abstractOptional: "Abstract (optional)",
      abstractTooltip: "Ein Abstract fasst Ihre geplante Arbeit in 150–250 Wörtern zusammen: Problemstellung, Zielsetzung, Methodik und erwartete Ergebnisse. Er hilft Prüfer:innen, das Thema schnell einzuschätzen.",
      remove: "Entfernen",
      noFbProgrammes: "Für {fb} sind noch keine {type}-Studiengänge hinterlegt.",
      colloquiumStatusLabel: "Status",
      colloquiumLocation: "Ort",
      colloquiumNotes: "Notizen",
      colloquiumNoLocation: "Kein Ort angegeben",
      colloquiumTitle: "Kolloquium",
      colloquiumDate: "Datum",
      colloquiumScheduled: "Geplant",
      colloquiumCompleted: "Abgeschlossen",
      colloquiumCancelled: "Abgesagt",
      myProfile: "Mein Profil",
      logout: "Abmelden",
      changePassword: "Passwort ändern",
      changePasswordTitle: "Passwort ändern",
      currentPasswordLabel: "Aktuelles Passwort",
      newPasswordLabel: "Neues Passwort",
      confirmNewPasswordLabel: "Neues Passwort bestätigen",
      passwordChangedSuccess: "Passwort erfolgreich geändert.",
      passwordSaving: "Wird gespeichert...",
      cancel: "Abbrechen",
      close: "Schließen",
      passwordMismatch2: "Die neuen Passwörter stimmen nicht überein.",
      passwordTooShort2: "Das neue Passwort muss mindestens 8 Zeichen lang sein.",
      // Formular & Übersetzungen
      loading: "Wird geladen…",
      // Anfrage zurückziehen
      withdrawRequest: "Anfrage zurückziehen",
      withdrawConfirmTitle: "Anfrage zurückziehen?",
      withdrawConfirmDesc: "Diese Anfrage wird unwiderruflich zurückgezogen. Die Prüfer:in wird nicht mehr benachrichtigt.",
      withdrawBtn: "Zurückziehen",
      withdrawSuccess: "Anfrage wurde zurückgezogen.",
      withdrawError: "Anfrage konnte nicht zurückgezogen werden.",
      openRequestBlockTitle: "Offene Anfrage vorhanden",
      openRequestBlockDesc: "Sie haben bereits eine offene Betreuungsanfrage. Bitte warten Sie auf eine Antwort oder ziehen Sie die bestehende Anfrage zurück, bevor Sie eine neue stellen.",
      openRequestBlockBtn: "Meine Anfragen anzeigen",
      historyRequestDate: "Eingereicht am",
      historyFirstExaminer: "Kontaktierte Erstbetreuung",
    },
    // Examiner Dashboard
    examiner: {
      title: "Prüfer:innen-Dashboard",
      requests: "Anfragen",
      profile: "Profil",
      colloquiums: "Kolloquium",
      history: "Verlauf",
      accept: "Annehmen",
      reject: "Ablehnen",
      downloadExpose: "Exposé herunterladen (PDF)",
      noRequests: "Keine offenen Anfragen.",
      programmes: "Prüfungsstudiengänge",
      toastAccepted: "Anfrage angenommen!",
      toastRejected: "Anfrage abgelehnt.",
      toastProfileSaved: "Profil gespeichert!",
      toastEmailSaved: "Alternative E-Mail gespeichert!",
      toastRoleSaved: "Prüfer:innen-Rolle gespeichert!",
      toastOnboardingDone: "Profil eingerichtet – willkommen!",
      statsTotal: "Gesamt",
      statsOpen: "Offen",
      statsAccepted: "Angenommen",
      statsMatched: "Zugeteilt",
      colStatusScheduled: "Geplant",
      colStatusCompleted: "Abgeschlossen",
      colStatusCancelled: "Abgesagt",
      auditThesisCreated: "Anfrage eingereicht",
      auditStatusChanged: "Status geändert",
      auditExaminerAccepted: "Prüfer:in hat angenommen",
      auditExaminerRejected: "Prüfer:in hat abgelehnt",
      auditFirstAssigned: "Erstprüfer:in zugewiesen",
      auditSecondAssigned: "Zweitprüfer:in zugewiesen",
      auditColloquiumCreated: "Kolloquium angelegt",
      auditDeadlineSet: "Abgabefrist gesetzt",
      // ExaminerProfile
      profileLoading: "Profil wird geladen...",
      profileNotFound: "Profil nicht gefunden",
      profileNotFoundDesc: "Diese Prüfer:in existiert nicht oder hat noch kein Profil angelegt.",
      backHome: "← Zurück zur Startseite",
      examinerLabel: "Prüfer:in",
      editProfile: "Profil bearbeiten",
      editProfileTitle: "Profil bearbeiten",
      photoAlt: "Profilfoto",
      unknownName: "Unbekannt",
      firstExaminerLabel: "Erstprüfer:in",
      secondExaminerLabel: "Zweitprüfer:in",
      supervisionCapacity: "Bis zu {n} Betreuungen",
      supervisionLanguages: "Betreuungssprachen",
      supervisionRequest: "Betreuungsanfrage stellen",
      supervisionRequestDesc: "Reichen Sie Ihre Themenidee ein und wählen Sie {name} als Prüfer:in.",
      submitRequest: "Anfrage einreichen",
      incompleteProfile: "Dieses Profil wurde noch nicht vollständig ausgefüllt.",
      fieldDepartment: "Fachbereich",
      fieldBio: "Kurzbiografie",
      fieldBioPlaceholder: "Beschreiben Sie Ihre Forschungsschwerpunkte...",
      fieldResearch: "Forschungsschwerpunkte",
      fieldOfficeHours: "Sprechzeiten",
      fieldWebsite: "Website / Profilseite",
      fieldTags: "Themen-Tags (kommagetrennt)",
      fieldLanguages: "Sprachen (kommagetrennt)",
      fieldMaxSupervisions: "Max. Betreuungen",
      saveBtn: "Speichern",
      savingBtn: "Wird gespeichert...",
      cancelBtn: "Abbrechen",
      toastPhotoUploaded: "Profilfoto erfolgreich hochgeladen.",
      toastUploadFailed: "Upload fehlgeschlagen",
      toastOnlyImages: "Nur Bilddateien sind erlaubt.",
      toastFileTooLarge: "Maximale Dateigröße: 5 MB.",
      loginBtn: "Anmelden",
      researchFocusSection: "Forschungsschwerpunkte",
    },
    pav: {
      title: "PAV-Dashboard",
      unassigned: "Unzugeteilte Studierende",
      myProgrammes: "Meine Studiengänge",
      proposeExaminer: "Prüfer:in vorschlagen",
      directAssign: "Direkt zuweisen",
      sendRequest: "Anfrage senden",
      sending: "Wird gesendet…",
      assigning: "Wird zugewiesen…",
      successPropose: "Anfrage erfolgreich versendet.",
      successAssign: "Prüfer:in wurde direkt zugewiesen.",
      role: "Rolle",
      firstExaminer: "Erstprüfer:in",
      secondExaminer: "Zweitprüfer:in",
      selectExaminer: "Prüfer:in auswählen…",
      selectRole: "Rolle wählen…",
      noUnassigned: "Keine unzugeteilten Anträge in Ihren Studiengängen.",
      noProgrammes: "Noch keine Studiengänge zugewiesen.",
      addProgramme: "Hinzufügen",
      removeProgramme: "Entfernen",
      bachelor: "Bachelor",
      master: "Master",
      proposalNote: "Im Tab \"Unzugeteilte Studierende\" werden dann nur Anträge dieser Studiengänge angezeigt.",
    },
    dean: {
      title: "Dekanat-Dashboard",
      allRequests: "Alle Anfragen",
      csvExport: "CSV-Export",
      exporting: "Wird exportiert…",
      statistics: "Statistiken",
      search: "Titel, Studierende:r, Studiengang…",
      filterStatus: "Status filtern",
      total: "Gesamt",
      pending: "Ausstehend",
      matched: "Zugeteilt",
      accepted: "Angenommen",
      rejected: "Abgelehnt",
      dean: "Dekan:in",
      viceDean: "Prodekan:in",
      admin: "Admin",
      language_de: "Deutsch",
      language_en: "Englisch",
      confirmed: "Bestätigt",
      allStatus: "Alle Status",
      searchPlaceholder: "Titel, Studierende:r, Studiengang…",
      colTopic: "Thema",
      colStudent: "Studierende:r",
      colDepartment: "Studiengang",
      colDegree: "Abschluss",
      colStatus: "Status",
      colSubmitted: "Eingereicht",
      clickForDetails: "Klicken Sie auf eine Zeile, um Details anzuzeigen.",
      stats: {
        title: "Statistik-Dashboard",
        subtitle: "Kennzahlen und Auswertungen für das Dekanat",
        totalRequests: "Anfragen gesamt",
        openRequests: "Offene Anfragen",
        avgProcessingTime: "Ø Bearbeitungszeit",
        completionRate: "Abschlussquote",
        days: "Tage",
        byStatus: "Anträge nach Status",
        byProgramme: "Anträge nach Studiengang",
        byMonth: "Anträge pro Monat (letzte 12 Monate)",
        examinerLoad: "Prüfer:innen-Auslastung (Top 10)",
        examinerName: "Prüfer:in",
        current: "Aktuell",
        max: "Max",
        utilization: "Auslastung",
        noData: "Keine Daten vorhanden.",
        loading: "Wird geladen…",
        backToDashboard: "Zurück zum Dashboard",
      },
    },
    superadmin: {
      title: "Superadmin-Dashboard",
      tabs: {
        overview: "Übersicht",
        users: "Nutzer:innen",
        programmes: "Studiengänge",
        settings: "Einstellungen",
        emailTemplates: "E-Mail-Vorlagen",
      },
      examinerManagement: "Prüferinnen-Verwaltung",
      manageExaminerProfiles: "Verwalten Sie die Profile und Status von Prüfer:innen",
      editProfile: "Profil bearbeiten",
      profileUpdated: "Profil erfolgreich aktualisiert",
      statusUpdated: "Status erfolgreich aktualisiert",
      confirmStatusChange: "Status ändern?",
      statusChangeWarning: "Wenn Sie eine Prüfer:in deaktivieren, kann sie keine neuen Anfragen mehr erhalten.",
      noExaminers: "Keine Prüfer:innen gefunden",
      department: "Abteilung",
      bio: "Biografie",
      researchFocus: "Forschungsschwerpunkt",
      maxSupervisions: "Max. Betreuungen",
      emailTemplates: {
        title: "E-Mail-Vorlagen",
        subtitle: "Bearbeiten Sie die automatisch versendeten E-Mails.",
        edit: "Bearbeiten",
        save: "Speichern",
        cancel: "Abbrechen",
        subject: "Betreff",
        htmlBody: "HTML-Inhalt",
        textBody: "Text-Inhalt (Fallback)",
        preview: "Vorschau",
        placeholders: "Verfügbare Platzhalter",
        saving: "Wird gespeichert…",
        successSave: "Vorlage gespeichert.",
        errorSave: "Fehler beim Speichern.",
        noTemplates: "Keine Vorlagen vorhanden.",
      },
    },
    onboarding: {
      title: "Willkommen bei Thesis Match Maker",
      subtitle: "Bitte vervollständigen Sie Ihr Profil, um Betreuungsanfragen zu erhalten.",
      step1: "Willkommen",
      step2: "Profildaten",
      step3: "Foto",
      step4: "Studiengänge",
      step5: "Kapazität",
      next: "Weiter",
      back: "Zurück",
      finish: "Abschließen",
      skip: "Überspringen",
      academicTitle: "Akademischer Titel",
      department: "Abteilung / Fachbereich",
      bio: "Kurzbeschreibung",
      researchFocus: "Forschungsschwerpunkt",
      officeHours: "Sprechzeiten",
      website: "Website",
      uploadPhoto: "Foto hochladen",
      maxSupervisions: "Maximale Betreuungsanzahl",
      isSecondExaminer: "Als Zweitprüfer:in verfügbar",
      selectProgrammes: "Studiengänge auswählen",
      completing: "Wird abgeschlossen…",
      successComplete: "Profil erfolgreich abgeschlossen!",
    },
    directory: {
      title: "Prüfer:innen-Verzeichnis",
      subtitle: "Alle verfügbaren Prüfer:innen des Fachbereichs 3",
      search: "Name, Fachgebiet oder Studiengang suchen…",
      filterProgramme: "Studiengang",
      filterRole: "Rolle",
      allProgrammes: "Alle Studiengänge",
      allRoles: "Alle Rollen",
      firstExaminer: "Erstprüfer:in",
      secondExaminer: "Zweitprüfer:in",
      noResults: "Keine Prüfer:innen gefunden.",
      capacity: "Kapazität",
      researchFocus: "Forschungsschwerpunkt",
      officeHours: "Sprechzeiten",
      website: "Website",
      requestSupervision: "Betreuung anfragen",
      loginRequired: "Anmeldung erforderlich",
      loginRequiredDesc: "Das Prüfer:innen-Verzeichnis ist nur für angemeldete Nutzer:innen der HTW Berlin zugänglich.",
      loginBtn: "Jetzt anmelden",
      backHome: "← Zurück zur Startseite",
      back: "← Zurück",
      directoryTitle: "Prüfer:innen-Verzeichnis",
      directorySubtitle: "Finden Sie die passende Betreuung für Ihre Abschlussarbeit an der HTW Berlin.",
      registered: "Prüfer:innen registriert",
      searchPlaceholder: "Name, Fachbereich, Thema suchen...",
      allProgrammesOpt: "Alle Studiengänge",
      allCapacities: "Alle Kapazitäten",
      freeCapacity: "Freie Kapazität",
      partialCapacity: "Teilweise belegt",
      roleAll: "Alle",
      roleFirst: "Erstprüfer:in",
      roleSecond: "Zweitprüfer:in",
      results: "Ergebnis",
      resultsPlural: "Ergebnisse",
      noExaminers: "Keine Prüfer:innen gefunden",
      noExaminersFiltered: "Versuchen Sie es mit anderen Suchbegriffen oder Filtern.",
      noExaminersEmpty: "Noch keine Prüfer:innen registriert.",
      resetFilters: "Filter zurücksetzen",
      viewProfile: "Profil ansehen →",
      researchFocusLabel: "Forschungsschwerpunkt:",
      unknownName: "Unbekannt",
      fictitiousExample: "Fiktives Beispiel",
    },
    // Login Page
    login: {
      backToHome: "Zurück zur Startseite",
      welcomeTitle: "Willkommen",
      welcomeSubtitle: "Melden Sie sich an oder erstellen Sie ein neues Konto.",
      alreadyHaveAccount: "Bereits registriert? Jetzt anmelden.",
      noAccountYet: "Noch kein Konto?",
      signInTitle: "Anmelden",
      selectRoleTitle: "Welche Rolle trifft auf Sie zu?",
      selectRoleSubtitle: "Wählen Sie Ihre Rolle, um fortzufahren.",
      selectedRole: "Ausgewählte Rolle",
      changeRole: "Rolle ändern",
      whatToDo: "Was möchten Sie tun?",
      whatToDoSub: "Melden Sie sich an oder erstellen Sie ein neues Konto.",
      signIn: "Anmelden",
      signInSub: "Ich habe bereits ein Konto",
      register: "Registrieren",
      registerSub: "Neues Konto erstellen",
      back: "Zurück",
      emailLabel: "E-Mail-Adresse",
      passwordLabel: "Passwort",
      forgotPassword: "Passwort vergessen?",
      sendingReset: "Wird gesendet…",
      enterEmailFirst: "Bitte zuerst Ihre E-Mail-Adresse eingeben.",
      resetSent: "Eine E-Mail mit dem Reset-Link wurde gesendet. Bitte prüfen Sie Ihr Postfach.",
      signingIn: "Anmeldung läuft …",
      signInBtn: "Anmelden",
      privacyConsent: "Durch die Anmeldung stimmen Sie der Verarbeitung Ihrer Daten gemäß der Datenschutzerklärung der HTW Berlin zu.",
      signInDesc: "Melden Sie sich mit Ihrer E-Mail-Adresse und Ihrem Passwort an",
      pendingTitle: "Konto noch nicht freigeschaltet",
      pendingText: "Ihre Registrierung wurde eingereicht und wird derzeit von der Verwaltung der HTW Berlin geprüft. Sie erhalten eine Benachrichtigung, sobald Ihr Zugang aktiviert wurde.",
      pendingNote: "Bei Fragen wenden Sie sich bitte an die Studiengangs\u00adverwaltung.",
      rejectedTitle: "Registrierungsantrag abgelehnt",
      rejectedText: "Ihr Registrierungsantrag wurde von der Verwaltung der HTW Berlin abgelehnt. Bitte wenden Sie sich direkt an die Studiengangs\u00adverwaltung für weitere Informationen.",
      errorInvalidToken: "Der Anmeldelink ist ungültig oder abgelaufen. Bitte melden Sie sich erneut an.",
      errorGeneric: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
      loginFailed: "Anmeldung fehlgeschlagen",
      registerFailed: "Registrierung fehlgeschlagen",
      matrikelNr: "Matrikelnummer",
      matrikelNrRequired: "Bitte geben Sie Ihre Matrikelnummer an.",
      matrikelNrPlaceholder: "z.B. 123456",
      fullName: "Vollständiger Name",
      fullNamePlaceholder: "Vorname Nachname",
      passwordMin: "Mindestens 8 Zeichen",
      passwordRepeat: "Passwort wiederholen",
      confirmPassword: "Passwort bestätigen",
      passwordMismatch: "Die Passwörter stimmen nicht überein.",
      passwordTooShort: "Das Passwort muss mindestens 8 Zeichen lang sein.",
      emailDomainStudent: "Erlaubte E-Mail-Domain: @student.htw-berlin.de",
      emailDomainSecondExaminer: "Beliebige E-Mail-Adresse erlaubt.",
      emailDomainExaminer: "Erlaubte E-Mail-Domains: @htw-berlin.de oder @htw-berlin.com",
      emailDomainErrorStudent: "Studierende müssen sich mit ihrer Studierenden-E-Mail-Adresse (@student.htw-berlin.de) registrieren.",
      emailDomainErrorExaminer: "Bitte verwenden Sie Ihre HTW-Berlin-E-Mail-Adresse (@htw-berlin.de oder @htw-berlin.com) zur Registrierung.",
      pendingApproval: "Nach der Registrierung wird Ihr Konto von der Verwaltung der HTW Berlin geprüft und freigeschaltet. Sie können sich erst nach der Freischaltung anmelden.",
      createAccount: "Konto erstellen",
      createAccountTitle: "Konto erstellen",
      createAccountDesc: "Ihr Konto wird nach der Registrierung von der Verwaltung freigeschaltet.",
      registering: "Registrierung läuft …",
      registerPrivacyConsent: "Mit der Registrierung stimmen Sie der Verarbeitung Ihrer Daten gemäß der Datenschutzerklärung der HTW Berlin zu.",
      registrationSubmitted: "Registrierung eingereicht",
      registrationSubmittedDesc: "Ihr Konto wurde angelegt und wartet auf die Freischaltung durch die Verwaltung der HTW Berlin. Sie erhalten eine Benachrichtigung, sobald Ihr Zugang aktiviert wurde.",
      toLogin: "Zur Anmeldung",
      roleStudent: "Studierende:r",
      roleStudentDesc: "Ich möchte eine Abschlussarbeit anmelden und Prüfer:innen finden.",
      roleExaminer: "Prüfer:in",
      roleExaminerDesc: "Ich betreue Abschlussarbeiten als Erst- oder Zweitprüfer:in.",
      roleSecondExaminer: "Zweitprüfer:in",
      roleSecondExaminerDesc: "Ich betreue Abschlussarbeiten ausschließlich als Zweitprüfer:in (ohne Erstprüfer-Berechtigung).",
      roleAdmin: "Verwaltungsmitarbeiter:in",
      roleAdminDesc: "Ich bin in der Studiengangs- oder Prüfungsverwaltung tätig.",
      footer: "HTW Berlin – Hochschule für Technik und Wirtschaft Berlin",
      emailPlaceholderStudent: "vorname.nachname@student.htw-berlin.de",
      emailPlaceholderExaminer: "vorname.nachname@htw-berlin.de",
      emailPlaceholderSecondExaminer: "ihre.email@beispiel.de",
      emailPlaceholderLogin: "vorname.nachname@htw-berlin.de",
      passwordPlaceholder: "Ihr Passwort",
    },
    // Admin Dashboard
    admin: {
      title: "Verwaltungs-Dashboard",
      overview: "Übersicht",
      requests: "Alle Anfragen",
      audit: "Audit-Log",
      users: "Nutzerverwaltung",
      stats: "Statistiken",
      settings: "Einstellungen",
      colloquiums: "Kolloquium",
      totalRequests: "Anfragen gesamt",
      pending: "Ausstehend",
      matched: "Zugeordnet",
      users_count: "Nutzer:innen",
    },
    // Status
    status: {
      PENDING: "Ausstehend",
      ACCEPTED: "Angenommen",
      REJECTED: "Abgelehnt",
      MATCHED: "Zugeordnet",
    },
    // Common
    common: {
      save: "Speichern",
      cancel: "Abbrechen",
      delete: "Löschen",
      edit: "Bearbeiten",
      loading: "Wird geladen…",
      error: "Fehler",
      success: "Erfolgreich",
      confirm: "Bestätigen",
      back: "Zurück",
      search: "Suchen",
      filter: "Filtern",
      all: "Alle",
      noData: "Keine Daten vorhanden.",
      name: "Name",
      email: "E-Mail",
      status: "Status",
      actions: "Aktionen",
      active: "Aktiv",
      inactive: "Inaktiv",
      forbidden: "Zugriff verweigert",
      accessDenied: "Sie haben keinen Zugriff auf diesen Bereich.",
      backHome: "Zur Startseite",
      close: "Schließen",
      contact: "Kontakt",
      aboutMe: "Über mich",
    },
    // My Profile Page
    myProfilePage: {
      title: "Mein Profil",
      back: "Zurück",
      edit: "Bearbeiten",
      save: "Speichern",
      cancel: "Abbrechen",
      notSpecified: "Nicht angegeben",
      notChangeable: "Nicht änderbar",
      profileSaved: "Profil gespeichert",
      profileLoadError: "Profil konnte nicht geladen werden.",
      profileLoading: "Profil wird geladen…",
      backHome: "Zur Startseite",
      // Sektionen
      sectionPersonal: "Persönliche Daten",
      sectionOnline: "Online-Präsenz",
      sectionStudent: "Studierenden-Informationen",
      sectionExaminer: "Prüfer:innen-Informationen",
      sectionAdmin: "Verwaltungs-Informationen",
      sectionAccount: "Konto-Informationen",
      // Felder
      fieldFullName: "Vollständiger Name",
      fieldNamePlaceholder: "Vor- und Nachname",
      fieldEmail: "E-Mail-Adresse",
      fieldSecondEmail: "Zweite E-Mail-Adresse",
      fieldSecondEmailPlaceholder: "alternative@beispiel.de",
      fieldPhone: "Telefonnummer",
      fieldPhonePlaceholder: "+49 30 12345678",
      fieldDepartment: "Fachbereich",
      fieldDepartmentPlaceholder: "Bitte wählen…",
      fieldBio: "Über mich",
      fieldBioPlaceholder: "Kurze Beschreibung Ihrer Person, Interessen oder Schwerpunkte…",
      fieldBioChars: "{n}/1000 Zeichen",
      // Studierende
      fieldMatrikelNr: "Matrikelnummer",
      fieldMatrikelNrPlaceholder: "z.B. 567890",
      fieldThesisType: "Angestrebter Abschluss",
      fieldEnrollmentSemester: "Immatrikulationssemester",
      fieldEnrollmentSemesterPlaceholder: "z.B. WiSe 2022/23",
      fieldTargetSemester: "Zielsemester (Abschluss)",
      fieldTargetSemesterPlaceholder: "z.B. SoSe 2025",
      // Prüfer:innen
      fieldAcademicTitle: "Akademischer Titel",
      fieldAcademicTitlePlaceholder: "z.B. Prof. Dr.",
      fieldOfficeRoom: "Büro / Raum",
      fieldOfficeRoomPlaceholder: "z.B. Gebäude C, Raum 123",
      fieldOfficeHours: "Sprechstunden",
      fieldOfficeHoursPlaceholder: "z.B. Di 10–12 Uhr",
      fieldResearchTags: "Forschungsschwerpunkte",
      fieldResearchTagsPlaceholder: "Tag eingeben und Enter drücken…",
      fieldResearchTagsHint: "Enter oder Komma zum Hinzufügen · Backspace zum Löschen des letzten Tags",
      // Verwaltung
      fieldStaffId: "Personalnummer",
      fieldResponsibilityArea: "Zuständigkeitsbereich",
      fieldOfficeLocation: "Bürostandort",
      // Online-Präsenz
      fieldWebsite: "Website",
      fieldWebsitePlaceholder: "https://www.beispiel.de",
      fieldLinkedIn: "LinkedIn-Profil",
      fieldLinkedInPlaceholder: "https://www.linkedin.com/in/…",
      fieldResearchGate: "ResearchGate-Profil",
      fieldResearchGatePlaceholder: "https://www.researchgate.net/profile/…",
      fieldHtwProfile: "HTW Berlin Profil",
      fieldHtwProfilePlaceholder: "https://www.htw-berlin.de/hochschule/personen/…",
      fieldMiscLink: "Weiterer Link",
      fieldMiscLinkPlaceholder: "https://…",
      fieldBookingUrl: "Terminbuchungs-Link",
      fieldBookingUrlPlaceholder: "https://calendly.com/… oder ähnlich",
      fieldBookingLabel: "Termin buchen",
      // Avatar
      avatarUploadTitle: "Neues Profilfoto hochladen",
      avatarUploading: "Wird hochgeladen…",
      avatarSuccess: "Profilfoto erfolgreich aktualisiert",
      avatarDeleteTitle: "Profilfoto löschen",
      avatarDeleted: "Profilfoto wurde zurückgesetzt",
      avatarPreview: "Vorschau vergrößern",
      avatarTooLarge: "Datei zu groß – bitte max. 5 MB.",
      avatarInvalidFormat: "Ungültiges Format – erlaubt sind JPEG, PNG, WebP und GIF.",
      avatarReadError: "Datei konnte nicht gelesen werden.",
      avatarEncodeError: "Datei konnte nicht kodiert werden.",
      avatarReadFailed: "Fehler beim Lesen der Datei.",
      avatarUploadError: "Fehler beim Upload: {msg}",
      // Validierung
      urlInvalid: "Bitte eine gültige Webadresse eingeben (z.B. https://beispiel.de)",
      urlErrorBanner: "Einige Webadressen sind ungültig. Bitte korrigieren Sie diese, bevor Sie speichern.",
      urlSaveBlocked: "Bitte zuerst ungültige Webadressen korrigieren",
      // Konto
      memberSince: "Mitglied seit",
      lastLogin: "Letzter Login",
      // Profil-Link
      profileLink: "Profil-Link",
      profileLinkCopied: "Link in Zwischenablage kopiert",
      profileLinkCopyFailed: "Kopieren fehlgeschlagen",
      viewPublicProfile: "Profil ansehen",
      // Delete-Confirm
      avatarDeleteConfirmTitle: "Profilfoto löschen?",
      avatarDeleteConfirmDesc: "Das Profilfoto wird unwiderruflich entfernt.",
      avatarDeleteConfirmBtn: "Löschen",
    },
  },
  en: {
    // Navigation & Layout
    nav: {
      home: "Home",
      examiners: "Examiners",
      login: "Sign In",
      logout: "Sign Out",
      dashboard: "Dashboard",
      student: "Student",
      examiner: "Examiner",
      admin: "Administration",
      directory: "Examiner Directory",
      myProfile: "My Profile",
      changePassword: "Change Password",
      notifications: "Notifications",
      noNotifications: "No notifications",
      markAllRead: "Mark all as read",
      openNav: "Open navigation",
      loading: "Loading...",
    },
    // Landing Page
    landing: {
      title: "Thesis Match Maker",
      subtitle: "Find your 2 supervisors with your brilliant academic idea",
      tagline: "The central HTW Berlin platform for thesis supervision matching",
      loginBtn: "Sign In Now",
      loginMagicLink: "Sign in via Magic Link",
      loginManus: "Sign in via HTW Account",
      emailPlaceholder: "Your HTW email address",
      sendLink: "Send Magic Link",
      sending: "Sending…",
      linkSent: "Magic Link sent! Please check your inbox.",
      browseExaminers: "Browse Examiners",
      openArea: "Open area",
      fachbereich: "Department 3",
      heroDesc: "The central HTW Berlin platform for matching students with thesis supervisors – from the first supervision request to the colloquium.",
      startAsStudent: "Start as Student",
      examinerArea: "Examiner Area",
      features: {
        match: "Find Supervisors",
        matchDesc: "Find suitable first and second examiners for your thesis.",
        track: "Track Status",
        trackDesc: "Keep track of requests, deadlines, and the colloquium.",
        secure: "Secure & GDPR-Compliant",
        secureDesc: "All data is processed in accordance with GDPR and stored securely.",
      },
      roles: {
        title: "Who is the platform for?",
        subtitle: "Three roles – one platform",
        student: "Student",
        studentFeatures: ["Submit thesis topic", "Request examiners", "Track status", "Plan colloquium"],
        examiner: "Examiner",
        examinerFeatures: ["Manage requests", "Maintain capacity", "Review templates", "Colloquium calendar"],
        admin: "Administration",
        adminFeatures: ["Admission workflow", "File management", "Audit log"],
      },
      process: {
        label: "The Process",
        title: "From idea to certificate",
        steps: [
          { number: "01", title: "Matchmaking", description: "Submit your topic and contact suitable examiners." },
          { number: "02", title: "Admission", description: "Administration checks prerequisites and grants official admission." },
          { number: "03", title: "Submission", description: "Upload your thesis by 11:59 PM on the submission deadline." },
          { number: "04", title: "Review Phase", description: "First and second examiners write their reviews independently." },
          { number: "05", title: "Colloquium", description: "Schedule finding, room booking, and invitation with calendar attachment." },
          { number: "06", title: "Completion", description: "Minutes, grade sheet, and certificate with digital signature." },
        ],
      },
      tech: {
        label: "Technical Framework",
        title: "Self-hosted. Sovereign. Secure.",
        desc: "The platform runs entirely under",
        descSuffix: "– without external authentication services or US cloud providers.",
        items: [
          { title: "On-Premise Hosting", desc: "Full data sovereignty, no external intermediaries.", icon: "🏗️" },
          { title: "SMTP Authentication", desc: "Login and notifications directly via the HTW mail server.", icon: "✉️" },
          { title: "GDPR-Compliant", desc: "Student phone numbers remain invisible to fellow students.", icon: "🔒" },
          { title: "JWT-Secured CTAs", desc: "Examiners can respond to requests via email link without logging in.", icon: "🔑" },
        ],
      },
      footer: {
        forStudents: "For Students",
        forExaminers: "For Examiners",
        contact: "Contact",
        aboutMe: "About Me",
        studentLinks: ["Find examiners", "Submit topic", "Submission portal", "Plan colloquium", "FAQ & Guide"],
        examinerLinks: ["Manage requests", "Maintain availability", "Review templates", "LVVO export", "Committee tools"],
        imprint: "Imprint",
        privacy: "Privacy",
        accessibility: "Accessibility",
        copyright: "© 2026 HTW Berlin",
      },
    },
    // Student Dashboard
    student: {
      title: "Student Dashboard",
      newRequest: "New Request",
      myRequests: "My Requests",
      noRequests: "No requests submitted yet.",
      submitRequest: "Submit Request",
      thesisTitle: "Thesis Title",
      description: "Description",
      department: "Department",
      degreeType: "Degree Type",
      targetSemester: "Target Semester",
      language: "Language",
      uploadExpose: "Upload Expose (PDF)",
      uploading: "Uploading...",
      uploadSuccess: "Expose uploaded successfully!",
      deadline: "Submission Deadline",
      downloadIcs: "Download Calendar Event (.ics)",
      colloquiums: "Colloquium",
      history: "History",
      // Request form
      draftRestore: "You have an incomplete draft. Would you like to restore it?",
      draftRestoreBtn: "Restore",
      draftDiscardBtn: "Discard",
      topicQuestion: "How would you like to receive your topic?",
      ownTopic: "I have my own proposal",
      ownTopicDesc: "You bring a specific topic. Title, description and expose will be requested.",
      assignedTopic: "I would like to be assigned a topic",
      assignedTopicDesc: "The examiner suggests a suitable topic. Only required fields will be requested.",
      exposeHint: "The expose is a ~2-page document summarising your topic, problem statement and planned approach. It is optional but increases your chances of acceptance.",
      pdfSelect: "Select PDF...",
      pleaseSelectSemester: "Please select a target semester.",
      pleaseSelectExaminer: "Please select a preferred examiner.",
      pleaseSelect: "-- Please select --",
      noProgForSelection: "No study programmes available for this selection",
      degreeFromProfile: "Degree type taken from your profile – cannot be changed.",
      semesterFromProfile: "Automatically taken from your profile – cannot be changed.",
      profileDataLabel: "Profile data (read-only)",
      profileDataHint: "Department, study programme and degree type are taken from your profile and cannot be changed here.",
      noProgrammeTitle: "No study programme set in profile",
      noProgrammeDesc: "Please set your study programme in your profile before submitting a request.",
      firstExaminer: "Select first examiner",
      firstExaminerDesc: "Select your preferred first examiner. This person will be contacted by email and must agree.",
      secondExaminerNote: "Selecting a second examiner is only possible after the first examiner has agreed.",
      noPreference: "No preference – second examiner can be assigned",
      availableAfterFirst: "Available after first examiner confirms",
      selectSecondExaminer: "Select second examiner",
      secondExaminerAvailable: "You can now indicate your preference for the second examiner.",
      secondPrefSaved: "Second examiner preference saved.",
      noExaminersFound: "No examiners found.",
      searchExaminer: "Search examiner...",
      nextSteps: "Next Steps",
      nextStepsDesc: "Submit your thesis idea and find suitable examiners for your thesis. The system will notify you by email about all status changes.",
      addToCalendar: "Add to calendar (.ics)",
      auditStatusChanged: "Status changed",
      auditExaminerAccepted: "Examiner accepted",
      auditExaminerRejected: "Examiner rejected",
      auditFirstAssigned: "First examiner assigned",
      auditSecondAssigned: "Second examiner assigned",
      selectRequest: "Select request",
      noHistory: "No entries yet.",
      reason: "Reason",
      findExaminers: "Find Examiners",
      submitIdea: "Submit Thesis Idea",
      submitIdeaDesc: "Describe your thesis idea. Admins and examiners will be notified.",
      browseExaminers: "Available Examiners",
      browseExaminersDesc: "Browse profiles and find suitable supervisors for your thesis.",

      topicSelection: "Topic Selection",
      ownTopicLabel: "Own Proposal",
      assignedTopicLabel: "Topic Assignment Requested",
      topicSection: "Topic",
      abstractLabel: "Abstract",
      exposeLabel: "Exposé",
      conditionsSection: "General Conditions",
      departmentField: "Department / Study Programme",
      targetSemesterField: "Target Semester",
      preferredExaminer: "Preferred Examiner",
      degreeField: "Degree Type",
      languageField: "Language",
      notSpecified: "Not specified",
      notSelected: "Not selected",
      editBtn: "Edit",
      printBtn: "Save as PDF / Print",
      submitNow: "Submit Now",
      previewSubmit: "Preview & Submit",
      printHeader: "Supervision Request – Summary",
      degreeSection: "Degree Type",
      fachbereichLabel: "Department",
      studyProgramLabel: "Study Programme",
      semesterLabel: "Planned Thesis Semester",
      thesisLanguageLabel: "Thesis Language",
      thesisLangDe: "German",
      thesisLangEn: "English",
      firstExaminerLabel: "First Examiner",
      capacityFull: "Fully booked",
      capacityAlmost: "Almost full",
      exposeView: "View Exposé",
      exposeReplace: "Replace",
      exposeUploadBtn: "Upload Exposé",
      exposeUploadSuccess: "Exposé uploaded successfully!",
      exposeUploadFailed: "Upload failed",
      exposeFileTooLarge: "File is too large (max. 16 MB).",
      exposePdfOnly: "Only PDF files are allowed.",
      secondExaminerTitle: "Select Second Examiner",
      firstExaminerAccepted: "First examiner has confirmed",
      currentPref: "Current preference",
      save: "Save",
      noRequestsTitle: "No requests yet",
      noRequestsDesc: "Submit your first thesis idea to get started.",
      colStatusScheduled: "Scheduled",
      colStatusCompleted: "Completed",
      colStatusCancelled: "Cancelled",
      historyTitle: "History",
      historySelectRequest: "Select request",
      historyPlease: "-- Please select --",
      historyNoEntries: "No entries yet.",
      historyReason: "Reason",
      auditThesisCreated: "Request submitted",
      auditColloquiumCreated: "Colloquium created",
      auditDeadlineSet: "Submission deadline set",
      tabRequests: "My Requests",
      tabNew: "Submit New Request",
      tabExaminers: "Find Examiners",
      tabColloquiums: "My Colloquium",
      tabHistory: "Status History",
      myColloquium: "My Colloquium",
      noColloquiums: "No colloquium scheduled yet.",
      abstractOptional: "Abstract (optional)",
      abstractTooltip: "An abstract summarises your planned work in 150–250 words: problem statement, objectives, methodology and expected results. It helps examiners quickly assess the topic.",
      remove: "Remove",
      noFbProgrammes: "No {type} programmes registered for {fb} yet.",
      colloquiumStatusLabel: "Status",
      colloquiumLocation: "Location",
      colloquiumNotes: "Notes",
      colloquiumNoLocation: "No location specified",
      colloquiumTitle: "Colloquium",
      colloquiumDate: "Date",
      colloquiumScheduled: "Scheduled",
      colloquiumCompleted: "Completed",
      colloquiumCancelled: "Cancelled",
      myProfile: "My Profile",
      logout: "Sign Out",
      changePassword: "Change Password",
      changePasswordTitle: "Change Password",
      currentPasswordLabel: "Current Password",
      newPasswordLabel: "New Password",
      confirmNewPasswordLabel: "Confirm New Password",
      passwordChangedSuccess: "Password changed successfully.",
      passwordSaving: "Saving...",
      cancel: "Cancel",
      close: "Close",
      passwordMismatch2: "The new passwords do not match.",
      passwordTooShort2: "The new password must be at least 8 characters long.",
      // Form & Translations
      loading: "Loading…",
      fileTooLarge: "File is too large. Please upload a PDF file with a maximum size of 5 MB.",
      submitting: "Submitting…",
      requestSubmitted: "Request submitted successfully!",
      validationTitle: "Please enter a title.",
      validationTitleShort: "The title should be at least 10 characters long.",
      validationDesc: "Please describe your topic.",
      validationDescShort: "The description should be at least 30 characters long.",
      validationSemester: "Please select a target semester.",
      validationExaminer: "Please select a preferred examiner.",
      validationFix: "Please correct the highlighted fields.",
      uploadFailed: "Exposé upload failed",
      previewTitle: "Preview Your Request",
      previewSubtitle: "Please review your details before final submission.",
      editBack: "Back to editing",
      // Withdraw request
      withdrawRequest: "Withdraw Request",
      withdrawConfirmTitle: "Withdraw Request?",
      withdrawConfirmDesc: "This request will be permanently withdrawn. The examiner will no longer be notified.",
      withdrawBtn: "Withdraw",
      withdrawSuccess: "Request has been withdrawn.",
      withdrawError: "The request could not be withdrawn.",
      openRequestBlockTitle: "Open request exists",
      openRequestBlockDesc: "You already have an open supervision request. Please wait for a response or withdraw the existing request before submitting a new one.",
      openRequestBlockBtn: "View my requests",
      historyRequestDate: "Submitted on",
      historyFirstExaminer: "Contacted primary supervisor",
    },
    // Examiner Dashboard
    examiner: {
      title: "Examiner Dashboard",
      requests: "Requests",
      profile: "Profile",
      colloquiums: "Colloquium",
      pending: "History",
      accept: "Accept",
      reject: "Reject",
      downloadExpose: "Download Exposé (PDF)",
      noRequests: "No open requests.",
      programmes: "Study Programmes",
      toastAccepted: "Request accepted!",
      toastRejected: "Request rejected.",
      toastProfileSaved: "Profile saved!",
      toastEmailSaved: "Alternative email saved!",
      toastRoleSaved: "Examiner role saved!",
      toastOnboardingDone: "Profile set up – welcome!",
      statsTotal: "Total",
      statsOpen: "Open",
      statsAccepted: "Accepted",
      statsMatched: "Matched",
      colStatusScheduled: "Scheduled",
      colStatusCompleted: "Completed",
      colStatusCancelled: "Cancelled",
      auditThesisCreated: "Request submitted",
      auditStatusChanged: "Status changed",
      auditExaminerAccepted: "Examiner accepted",
      auditExaminerRejected: "Examiner rejected",
      auditFirstAssigned: "First examiner assigned",
      auditSecondAssigned: "Second examiner assigned",
      auditColloquiumCreated: "Colloquium created",
      auditDeadlineSet: "Deadline set",
      // ExaminerProfile
      profileLoading: "Loading profile...",
      profileNotFound: "Profile not found",
      profileNotFoundDesc: "This examiner does not exist or has not yet set up a profile.",
      backHome: "← Back to Home",
      examinerLabel: "Examiner",
      editProfile: "Edit Profile",
      editProfileTitle: "Edit Profile",
      photoAlt: "Profile photo",
      unknownName: "Unknown",
      firstExaminerLabel: "First Examiner",
      secondExaminerLabel: "Second Examiner",
      supervisionCapacity: "Up to {n} supervisions",
      supervisionLanguages: "Supervision Languages",
      supervisionRequest: "Request Supervision",
      supervisionRequestDesc: "Submit your thesis idea and select {name} as your examiner.",
      submitRequest: "Submit Request",
      incompleteProfile: "This profile has not been fully completed yet.",
      fieldDepartment: "Department",
      fieldBio: "Short Biography",
      fieldBioPlaceholder: "Describe your research focus...",
      fieldResearch: "Research Focus",
      fieldOfficeHours: "Office Hours",
      fieldWebsite: "Website / Profile Page",
      fieldTags: "Topic Tags (comma-separated)",
      fieldLanguages: "Languages (comma-separated)",
      fieldMaxSupervisions: "Max. Supervisions",
      saveBtn: "Save",
      savingBtn: "Saving...",
      cancelBtn: "Cancel",
      toastPhotoUploaded: "Profile photo uploaded successfully.",
      toastUploadFailed: "Upload failed",
      toastOnlyImages: "Only image files are allowed.",
      toastFileTooLarge: "Maximum file size: 5 MB.",
      loginBtn: "Sign In",
      researchFocusSection: "Research Focus",
    },
    pav: {
      title: "PAV Dashboard",
      unassigned: "Unassigned Students",
      myProgrammes: "My Study Programmes",
      proposeExaminer: "Propose Examiner",
      directAssign: "Direct Assignment",
      sendRequest: "Send Request",
      sending: "Sending…",
      assigning: "Assigning…",
      successPropose: "Request sent successfully.",
      successAssign: "Examiner directly assigned.",
      role: "Role",
      firstExaminer: "First Examiner",
      secondExaminer: "Second Examiner",
      selectExaminer: "Select examiner…",
      selectRole: "Select role…",
      noUnassigned: "No unassigned requests in your study programmes.",
      noProgrammes: "No study programmes assigned yet.",
      addProgramme: "Add",
      removeProgramme: "Remove",
      bachelor: "Bachelor",
      master: "Master",
      proposalNote: "The \"Unassigned Students\" tab will then only show requests from these study programmes.",
    },
    dean: {
      title: "Dean's Dashboard",
      allRequests: "All Requests",
      csvExport: "CSV Export",
      exporting: "Exporting…",
      statistics: "Statistics",
      search: "Title, student, study programme…",
      filterStatus: "Filter by status",
      total: "Total",
      pending: "Pending",
      matched: "Matched",
      accepted: "Accepted",
      rejected: "Rejected",
      dean: "Dean",
      viceDean: "Vice Dean",
      admin: "Admin",
      language_de: "German",
      language_en: "English",
      confirmed: "Confirmed",
      allStatus: "All Statuses",
      searchPlaceholder: "Title, student, study programme…",
      colTopic: "Topic",
      colStudent: "Student",
      colDepartment: "Study Programme",
      colDegree: "Degree",
      colStatus: "Status",
      colSubmitted: "Submitted",
      clickForDetails: "Click on a row to view details.",
      stats: {
        title: "Statistics Dashboard",
        subtitle: "Key metrics and analytics for the dean's office",
        totalRequests: "Total Requests",
        openRequests: "Open Requests",
        avgProcessingTime: "Avg. Processing Time",
        completionRate: "Completion Rate",
        days: "days",
        byStatus: "Requests by Status",
        byProgramme: "Requests by Study Programme",
        byMonth: "Requests per Month (last 12 months)",
        examinerLoad: "Examiner Workload (Top 10)",
        examinerName: "Examiner",
        current: "Current",
        max: "Max",
        utilization: "Utilization",
        noData: "No data available.",
        loading: "Loading…",
        backToDashboard: "Back to Dashboard",
      },
    },
    superadmin: {
      title: "Superadmin Dashboard",
      tabs: {
        overview: "Overview",
        users: "Users",
        programmes: "Study Programmes",
        settings: "Settings",
        emailTemplates: "Email Templates",
      },
      examinerManagement: "Examiner Management",
      manageExaminerProfiles: "Manage examiner profiles and status",
      editProfile: "Edit Profile",
      profileUpdated: "Profile updated successfully",
      statusUpdated: "Status updated successfully",
      confirmStatusChange: "Change Status?",
      statusChangeWarning: "If you deactivate an examiner, they will no longer receive new requests.",
      noExaminers: "No examiners found",
      department: "Department",
      bio: "Biography",
      researchFocus: "Research Focus",
      maxSupervisions: "Max. Supervisions",
      emailTemplates: {
        title: "Email Templates",
        subtitle: "Edit the automatically sent emails.",
        edit: "Edit",
        save: "Save",
        cancel: "Cancel",
        subject: "Subject",
        htmlBody: "HTML Content",
        textBody: "Plain Text (Fallback)",
        preview: "Preview",
        placeholders: "Available Placeholders",
        saving: "Saving…",
        successSave: "Template saved.",
        errorSave: "Error saving template.",
        noTemplates: "No templates available.",
      },
    },
    onboarding: {
      title: "Welcome to Thesis Match Maker",
      subtitle: "Please complete your profile to receive supervision requests.",
      step1: "Welcome",
      step2: "Profile",
      step3: "Photo",
      step4: "Programmes",
      step5: "Capacity",
      next: "Next",
      back: "Back",
      finish: "Complete",
      skip: "Skip",
      academicTitle: "Academic Title",
      department: "Department",
      bio: "Short Description",
      researchFocus: "Research Focus",
      officeHours: "Office Hours",
      website: "Website",
      uploadPhoto: "Upload Photo",
      maxSupervisions: "Maximum Supervisions",
      isSecondExaminer: "Available as Second Examiner",
      selectProgrammes: "Select Study Programmes",
      completing: "Completing…",
      successComplete: "Profile completed successfully!",
    },
    directory: {
      title: "Examiner Directory",
      subtitle: "All available examiners of Department 3",
      search: "Search by name, field, or study programme…",
      filterProgramme: "Study Programme",
      filterRole: "Role",
      allProgrammes: "All Programmes",
      allRoles: "All Roles",
      firstExaminer: "First Examiner",
      secondExaminer: "Second Examiner",
      noResults: "No examiners found.",
      capacity: "Capacity",
      researchFocus: "Research Focus",
      officeHours: "Office Hours",
      website: "Website",
      requestSupervision: "Request Supervision",
      loginRequired: "Login Required",
      loginRequiredDesc: "The examiner directory is only accessible to registered users of HTW Berlin.",
      loginBtn: "Sign In Now",
      backHome: "← Back to Home",
      back: "← Back",
      directoryTitle: "Examiner Directory",
      directorySubtitle: "Find the right supervision for your thesis at HTW Berlin.",
      registered: "examiners registered",
      searchPlaceholder: "Search by name, department, topic...",
      allProgrammesOpt: "All Programmes",
      allCapacities: "All Capacities",
      freeCapacity: "Available",
      partialCapacity: "Partially booked",
      roleAll: "All",
      roleFirst: "First Examiner",
      roleSecond: "Second Examiner",
      results: "result",
      resultsPlural: "results",
      noExaminers: "No examiners found",
      noExaminersFiltered: "Try different search terms or filters.",
      noExaminersEmpty: "No examiners registered yet.",
      resetFilters: "Reset filters",
      viewProfile: "View profile →",
      researchFocusLabel: "Research focus:",
      unknownName: "Unknown",
      fictitiousExample: "Fictitious Example",
    },
    // Login Page
    login: {
      backToHome: "Back to Home",
      welcomeTitle: "Welcome",
      welcomeSubtitle: "Sign in or create a new account.",
      alreadyHaveAccount: "Already registered? Sign in.",
      noAccountYet: "No account yet?",
      signInTitle: "Sign In",
      selectRoleTitle: "Which role applies to you?",
      selectRoleSubtitle: "Select your role to continue.",
      selectedRole: "Selected Role",
      changeRole: "Change Role",
      whatToDo: "What would you like to do?",
      whatToDoSub: "Sign in or create a new account.",
      signIn: "Sign In",
      signInSub: "I already have an account",
      register: "Register",
      registerSub: "Create a new account",
      back: "Back",
      emailLabel: "Email Address",
      passwordLabel: "Password",
      forgotPassword: "Forgot password?",
      sendingReset: "Sending…",
      enterEmailFirst: "Please enter your email address first.",
      resetSent: "A reset link has been sent. Please check your inbox.",
      signingIn: "Signing in…",
      signInBtn: "Sign In",
      privacyConsent: "By signing in, you agree to the processing of your data in accordance with the HTW Berlin privacy policy.",
      signInDesc: "Sign in with your email address and password",
      pendingTitle: "Account not yet activated",
      pendingText: "Your registration has been submitted and is currently being reviewed by HTW Berlin administration. You will receive a notification once your account has been activated.",
      pendingNote: "If you have any questions, please contact the study programme administration.",
      rejectedTitle: "Registration request rejected",
      rejectedText: "Your registration request has been rejected by HTW Berlin administration. Please contact the study programme administration directly for further information.",
      errorInvalidToken: "The login link is invalid or has expired. Please sign in again.",
      errorGeneric: "An error occurred. Please try again.",
      loginFailed: "Sign in failed",
      registerFailed: "Registration failed",
      matrikelNr: "Student ID",
      matrikelNrRequired: "Please enter your student ID.",
      matrikelNrPlaceholder: "e.g. 123456",
      fullName: "Full Name",
      fullNamePlaceholder: "First Last",
      passwordMin: "At least 8 characters",
      passwordRepeat: "Repeat password",
      confirmPassword: "Confirm Password",
      passwordMismatch: "Passwords do not match.",
      passwordTooShort: "Password must be at least 8 characters long.",
      emailDomainStudent: "Allowed email domain: @student.htw-berlin.de",
      emailDomainSecondExaminer: "Any email address allowed.",
      emailDomainExaminer: "Allowed email domains: @htw-berlin.de or @htw-berlin.com",
      emailDomainErrorStudent: "Students must register with their student email address (@student.htw-berlin.de).",
      emailDomainErrorExaminer: "Please use your HTW Berlin email address (@htw-berlin.de or @htw-berlin.com) to register.",
      pendingApproval: "After registration, your account will be reviewed and activated by HTW Berlin administration. You can only sign in after activation.",
      createAccount: "Create Account",
      createAccountTitle: "Create Account",
      createAccountDesc: "Your account will be activated by administration after registration.",
      registering: "Registering…",
      registerPrivacyConsent: "By registering, you agree to the processing of your data in accordance with the HTW Berlin privacy policy.",
      registrationSubmitted: "Registration submitted",
      registrationSubmittedDesc: "Your account has been created and is awaiting activation by HTW Berlin administration. You will receive a notification once your account has been activated.",
      toLogin: "Go to Sign In",
      roleStudent: "Student",
      roleStudentDesc: "I want to register a thesis and find examiners.",
      roleExaminer: "Examiner",
      roleExaminerDesc: "I supervise theses as first or second examiner.",
      roleSecondExaminer: "Second Examiner",
      roleSecondExaminerDesc: "I supervise theses exclusively as second examiner (without first examiner authorization).",
      roleAdmin: "Administration Staff",
      roleAdminDesc: "I work in study programme or examination administration.",
      footer: "HTW Berlin – University of Applied Sciences",
      emailPlaceholderStudent: "firstname.lastname@student.htw-berlin.de",
      emailPlaceholderExaminer: "firstname.lastname@htw-berlin.de",
      emailPlaceholderSecondExaminer: "your.email@example.com",
      emailPlaceholderLogin: "firstname.lastname@htw-berlin.de",
      passwordPlaceholder: "Your password",
    },
    // Admin Dashboard
    admin: {
      title: "Administration Dashboard",
      overview: "Overview",
      requests: "All Requests",
      audit: "Audit Log",
      users: "User Management",
      stats: "Statistics",
      settings: "Settings",
      colloquiums: "Colloquium",
      totalRequests: "Total Requests",
      pending: "Pending",
      matched: "Matched",
      users_count: "Users",
    },
    // Status
    status: {
      PENDING: "Pending",
      ACCEPTED: "Accepted",
      REJECTED: "Rejected",
      MATCHED: "Matched",
    },
    // Common
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      loading: "Loading…",
      error: "Error",
      success: "Success",
      confirm: "Confirm",
      back: "Back",
      search: "Search",
      filter: "Filter",
      all: "All",
      noData: "No data available.",
      name: "Name",
      email: "Email",
      status: "Status",
      actions: "Actions",
      active: "Active",
      inactive: "Inactive",
      forbidden: "Access Denied",
      accessDenied: "You do not have access to this area.",
      backHome: "Back to Home",
      close: "Close",
      contact: "Contact",
      aboutMe: "About Me",
    },
    // My Profile Page
    myProfilePage: {
      title: "My Profile",
      back: "Back",
      edit: "Edit",
      save: "Save",
      cancel: "Cancel",
      notSpecified: "Not specified",
      notChangeable: "Cannot be changed",
      profileSaved: "Profile saved",
      profileLoadError: "Profile could not be loaded.",
      profileLoading: "Loading profile…",
      backHome: "Back to Home",
      // Sections
      sectionPersonal: "Personal Information",
      sectionOnline: "Online Presence",
      sectionStudent: "Student Information",
      sectionExaminer: "Examiner Information",
      sectionAdmin: "Administration Information",
      sectionAccount: "Account Information",
      // Fields
      fieldFullName: "Full Name",
      fieldNamePlaceholder: "First and last name",
      fieldEmail: "Email Address",
      fieldSecondEmail: "Secondary Email Address",
      fieldSecondEmailPlaceholder: "alternative@example.com",
      fieldPhone: "Phone Number",
      fieldPhonePlaceholder: "+49 30 12345678",
      fieldDepartment: "Department",
      fieldDepartmentPlaceholder: "Please select…",
      fieldBio: "About Me",
      fieldBioPlaceholder: "Brief description of yourself, interests or focus areas…",
      fieldBioChars: "{n}/1000 characters",
      // Student
      fieldMatrikelNr: "Student ID",
      fieldMatrikelNrPlaceholder: "e.g. 567890",
      fieldThesisType: "Target Degree",
      fieldEnrollmentSemester: "Enrollment Semester",
      fieldEnrollmentSemesterPlaceholder: "e.g. WiSe 2022/23",
      fieldTargetSemester: "Target Semester (Graduation)",
      fieldTargetSemesterPlaceholder: "e.g. SoSe 2025",
      // Examiner
      fieldAcademicTitle: "Academic Title",
      fieldAcademicTitlePlaceholder: "e.g. Prof. Dr.",
      fieldOfficeRoom: "Office / Room",
      fieldOfficeRoomPlaceholder: "e.g. Building C, Room 123",
      fieldOfficeHours: "Office Hours",
      fieldOfficeHoursPlaceholder: "e.g. Tue 10–12 am",
      fieldResearchTags: "Research Focus Areas",
      fieldResearchTagsPlaceholder: "Enter tag and press Enter…",
      fieldResearchTagsHint: "Enter or comma to add · Backspace to remove last tag",
      // Admin
      fieldStaffId: "Staff ID",
      fieldResponsibilityArea: "Area of Responsibility",
      fieldOfficeLocation: "Office Location",
      // Online Presence
      fieldWebsite: "Website",
      fieldWebsitePlaceholder: "https://www.example.com",
      fieldLinkedIn: "LinkedIn Profile",
      fieldLinkedInPlaceholder: "https://www.linkedin.com/in/…",
      fieldResearchGate: "ResearchGate Profile",
      fieldResearchGatePlaceholder: "https://www.researchgate.net/profile/…",
      fieldHtwProfile: "HTW Berlin Profile",
      fieldHtwProfilePlaceholder: "https://www.htw-berlin.de/hochschule/personen/…",
      fieldMiscLink: "Additional Link",
      fieldMiscLinkPlaceholder: "https://…",
      fieldBookingUrl: "Booking Link",
      fieldBookingUrlPlaceholder: "https://calendly.com/… or similar",
      fieldBookingLabel: "Book Appointment",
      // Avatar
      avatarUploadTitle: "Upload New Profile Photo",
      avatarUploading: "Uploading…",
      avatarSuccess: "Profile photo updated successfully",
      avatarDeleteTitle: "Delete Profile Photo",
      avatarDeleted: "Profile photo has been removed",
      avatarPreview: "Enlarge preview",
      avatarTooLarge: "File too large – max. 5 MB.",
      avatarInvalidFormat: "Invalid format – allowed: JPEG, PNG, WebP and GIF.",
      avatarReadError: "File could not be read.",
      avatarEncodeError: "File could not be encoded.",
      avatarReadFailed: "Error reading file.",
      avatarUploadError: "Upload error: {msg}",
      // Validation
      urlInvalid: "Please enter a valid web address (e.g. https://example.com)",
      urlErrorBanner: "Some web addresses are invalid. Please correct them before saving.",
      urlSaveBlocked: "Please fix invalid web addresses first",
      // Account
      memberSince: "Member since",
      lastLogin: "Last login",
      // Profile link
      profileLink: "Profile Link",
      profileLinkCopied: "Link copied to clipboard",
      profileLinkCopyFailed: "Copy failed",
      viewPublicProfile: "View Profile",
      // Delete confirm
      avatarDeleteConfirmTitle: "Delete Profile Photo?",
      avatarDeleteConfirmDesc: "The profile photo will be permanently removed.",
      avatarDeleteConfirmBtn: "Delete",
    },
  },
} as const;

export type Translations = typeof translations[Language];

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: typeof translations.de;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    try {
      return (localStorage.getItem("htw-lang") as Language) ?? "de";
    } catch {
      return "de";
    }
  });

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    try {
      localStorage.setItem("htw-lang", newLang);
    } catch {}
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] as typeof translations.de }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

/** Compact language switcher component */
export function LanguageSwitcher({ className = "" }: { className?: string }) {
  const { lang, setLang } = useLanguage();
  return (
    <div className={`flex items-center gap-1 ${className}`}>
      <button
        onClick={() => setLang("de")}
        className={`px-2 py-1 text-xs font-semibold rounded transition-colors ${
          lang === "de"
            ? "bg-[#76B900] text-white"
            : "text-gray-500 hover:text-gray-800"
        }`}
        aria-label="Deutsch"
      >
        DE
      </button>
      <span className="text-gray-300 text-xs">|</span>
      <button
        onClick={() => setLang("en")}
        className={`px-2 py-1 text-xs font-semibold rounded transition-colors ${
          lang === "en"
            ? "bg-[#76B900] text-white"
            : "text-gray-500 hover:text-gray-800"
        }`}
        aria-label="English"
      >
        EN
      </button>
    </div>
  );
}
