import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "de" | "en";

const translations = {
  de: {
    // Navigation & Layout
    nav: {
      home: "Startseite",
      examiners: "Prüfer:innen",
      login: "Anmelden",
      logout: "Abmelden",
      dashboard: "Dashboard",
      student: "Studierende:r",
      examiner: "Prüfer:in",
      admin: "Verwaltung",
      directory: "Prüfer:innen-Verzeichnis",
    },
    // Landing Page
    landing: {
      title: "Thesis Match Maker",
      subtitle: "Finden Sie Ihre 2 Betreuungspersonen für Ihre Abschlussarbeit",
      tagline: "Die Plattform der HTW Berlin zur Vermittlung von Abschlussarbeiten",
      loginBtn: "Jetzt anmelden",
      loginMagicLink: "Anmelden via Magic Link",
      loginManus: "Anmelden via HTW-Konto",
      emailPlaceholder: "Ihre HTW-E-Mail-Adresse",
      sendLink: "Magic Link senden",
      sending: "Wird gesendet…",
      linkSent: "Magic Link gesendet! Bitte prüfen Sie Ihr E-Mail-Postfach.",
      browseExaminers: "Prüfer:innen-Verzeichnis",
      openArea: "Bereich öffnen",
      fachbereich: "Fachbereich 3",
      heroDesc: "Die zentrale Plattform der HTW Berlin für das Matchmaking zwischen Studierenden und Prüfer:innen – von der ersten Betreuungsanfrage bis zum Kolloquium.",
      startAsStudent: "Als Studierende:r starten",
      examinerArea: "Prüfer:innen-Bereich",
      features: {
        match: "Betreuer:innen finden",
        matchDesc: "Finden Sie passende Erst- und Zweitprüfer:innen für Ihre Abschlussarbeit.",
        track: "Status verfolgen",
        trackDesc: "Behalten Sie den Überblick über Anfragen, Deadlines und Kolloquien.",
        secure: "Sicher & Datenschutzkonform",
        secureDesc: "Alle Daten werden gemäß DSGVO verarbeitet und sicher gespeichert.",
      },
      roles: {
        title: "Für wen ist die Plattform?",
        subtitle: "Drei Rollen – eine Plattform",
        student: "Studierende:r",
        studentFeatures: ["Thema einreichen", "Prüfer:innen anfragen", "Status verfolgen", "Kolloquium planen"],
        examiner: "Prüfer:in",
        examinerFeatures: ["Anfragen verwalten", "Kapazität pflegen", "Gutachten-Vorlagen", "Kolloquiums-Kalender"],
        admin: "Verwaltung",
        adminFeatures: ["Zulassungs-Workflow", "Akte X", "Audit-Log"],
      },
      process: {
        label: "Der Ablauf",
        title: "Von der Idee bis zur Urkunde",
        steps: [
          { number: "01", title: "Matchmaking", description: "Thema einreichen und passende Prüfer:innen kontaktieren." },
          { number: "02", title: "Zulassung", description: "Verwaltung prüft Voraussetzungen und erteilt offizielle Zulassung." },
          { number: "03", title: "Abgabe", description: "Upload der Arbeit bis 23:59 des Abgabetermins mit Opt-ins." },
          { number: "04", title: "Gutachtenphase", description: "Erst- und Zweitprüfer:in verfassen unabhängig ihre Gutachten." },
          { number: "05", title: "Kolloquium", description: "Terminfindung, Raumbuchung und Einladung mit Kalender-Anhang." },
          { number: "06", title: "Abschluss", description: "Protokoll, Notenblatt und Urkunde mit digitaler Signatur." },
        ],
      },
      tech: {
        label: "Technischer Rahmen",
        title: "Selbstgehostet. Souverän. Sicher.",
        desc: "Die Plattform läuft vollständig unter",
        descSuffix: "– ohne externe Authentifizierungs-Dienste oder US-Cloud-Anbieter.",
        items: [
          { title: "On-Premise Hosting", desc: "Vollständige Datenhoheit, keine externen Zwischenebenen.", icon: "🏗️" },
          { title: "SMTP-Authentifizierung", desc: "Login und Benachrichtigungen direkt über den HTW-Mailserver.", icon: "✉️" },
          { title: "DSGVO-konform", desc: "Studentische Telefonnummern bleiben für Kommilitonen unsichtbar.", icon: "🔒" },
          { title: "JWT-gesicherte CTAs", desc: "Prüfer:innen können Anfragen per E-Mail-Link ohne Login beantworten.", icon: "🔑" },
        ],
      },
      footer: {
        forStudents: "Für Studierende",
        forExaminers: "Für Prüfer:innen",
        contact: "Kontakt",
        studentLinks: ["Prüfer:innen finden", "Thema einreichen", "Abgabeportal", "Kolloquium planen", "FAQ & Leitfaden"],
        examinerLinks: ["Anfragen verwalten", "Verfügbarkeit pflegen", "Gutachten-Vorlagen", "LVVO-Export", "Kommissions-Tools"],
        imprint: "Impressum",
        privacy: "Datenschutz",
        accessibility: "Barrierefreiheit",
        copyright: "© 2026 HTW Berlin",
      },
    },
    // Student Dashboard
    student: {
      title: "Studierenden-Dashboard",
      newRequest: "Neue Anfrage",
      myRequests: "Meine Anfragen",
      noRequests: "Noch keine Anfragen eingereicht.",
      submitRequest: "Anfrage einreichen",
      thesisTitle: "Titel der Abschlussarbeit",
      description: "Beschreibung",
      department: "Fachbereich",
      degreeType: "Abschlussart",
      targetSemester: "Zielsemester",
      language: "Sprache",
      uploadExpose: "Exposé hochladen (PDF)",
      uploading: "Wird hochgeladen…",
      uploadSuccess: "Exposé erfolgreich hochgeladen!",
      deadline: "Abgabefrist",
      downloadIcs: "Termin herunterladen (.ics)",
      colloquiums: "Kolloquien",
      history: "Verlauf",
    },
    // Examiner Dashboard
    examiner: {
      title: "Prüfer:innen-Dashboard",
      requests: "Anfragen",
      profile: "Profil",
      colloquiums: "Kolloquien",
      history: "Verlauf",
      accept: "Annehmen",
      reject: "Ablehnen",
      downloadExpose: "Exposé herunterladen (PDF)",
      noRequests: "Keine offenen Anfragen.",
      programmes: "Prüfungsstudiengänge",
      toastAccepted: "Anfrage angenommen!",
      toastRejected: "Anfrage abgelehnt.",
      toastProfileSaved: "Profil gespeichert!",
      toastEmailSaved: "Alternative E-Mail gespeichert!",
      toastRoleSaved: "Prüfer:innen-Rolle gespeichert!",
      toastOnboardingDone: "Profil eingerichtet – willkommen!",
      statsTotal: "Gesamt",
      statsOpen: "Offen",
      statsAccepted: "Angenommen",
      statsMatched: "Zugeteilt",
      colStatusScheduled: "Geplant",
      colStatusCompleted: "Abgeschlossen",
      colStatusCancelled: "Abgesagt",
      auditThesisCreated: "Anfrage eingereicht",
      auditStatusChanged: "Status geändert",
      auditExaminerAccepted: "Prüfer:in hat angenommen",
      auditExaminerRejected: "Prüfer:in hat abgelehnt",
      auditFirstAssigned: "Erstprüfer:in zugewiesen",
      auditSecondAssigned: "Zweitprüfer:in zugewiesen",
      auditColloquiumCreated: "Kolloquium angelegt",
      auditDeadlineSet: "Abgabefrist gesetzt",
    },
    pav: {
      title: "PAV-Dashboard",
      unassigned: "Unzugeteilte Studierende",
      myProgrammes: "Meine Studiengänge",
      proposeExaminer: "Prüfer:in vorschlagen",
      directAssign: "Direkt zuweisen",
      sendRequest: "Anfrage senden",
      sending: "Wird gesendet…",
      assigning: "Wird zugewiesen…",
      successPropose: "Anfrage erfolgreich versendet.",
      successAssign: "Prüfer:in wurde direkt zugewiesen.",
      role: "Rolle",
      firstExaminer: "Erstprüfer:in",
      secondExaminer: "Zweitprüfer:in",
      selectExaminer: "Prüfer:in auswählen…",
      selectRole: "Rolle wählen…",
      noUnassigned: "Keine unzugeteilten Anträge in Ihren Studiengängen.",
      noProgrammes: "Noch keine Studiengänge zugewiesen.",
      addProgramme: "Hinzufügen",
      removeProgramme: "Entfernen",
      bachelor: "Bachelor",
      master: "Master",
      proposalNote: "Im Tab \"Unzugeteilte Studierende\" werden dann nur Anträge dieser Studiengänge angezeigt.",
    },
    dean: {
      title: "Dekanat-Dashboard",
      allRequests: "Alle Anfragen",
      csvExport: "CSV-Export",
      exporting: "Wird exportiert…",
      statistics: "Statistiken",
      search: "Titel, Studierende:r, Studiengang…",
      filterStatus: "Status filtern",
      total: "Gesamt",
      pending: "Ausstehend",
      matched: "Zugeteilt",
      accepted: "Angenommen",
      rejected: "Abgelehnt",
      dean: "Dekan:in",
      viceDean: "Prodekan:in",
      admin: "Admin",
      language_de: "Deutsch",
      language_en: "Englisch",
      confirmed: "Bestätigt",
      allStatus: "Alle Status",
      searchPlaceholder: "Titel, Studierende:r, Studiengang…",
      colTopic: "Thema",
      colStudent: "Studierende:r",
      colDepartment: "Studiengang",
      colDegree: "Abschluss",
      colStatus: "Status",
      colSubmitted: "Eingereicht",
      clickForDetails: "Klicken Sie auf eine Zeile, um Details anzuzeigen.",
      stats: {
        title: "Statistik-Dashboard",
        subtitle: "Kennzahlen und Auswertungen für das Dekanat",
        totalRequests: "Anfragen gesamt",
        openRequests: "Offene Anfragen",
        avgProcessingTime: "Ø Bearbeitungszeit",
        completionRate: "Abschlussquote",
        days: "Tage",
        byStatus: "Anträge nach Status",
        byProgramme: "Anträge nach Studiengang",
        byMonth: "Anträge pro Monat (letzte 12 Monate)",
        examinerLoad: "Prüfer:innen-Auslastung (Top 10)",
        examinerName: "Prüfer:in",
        current: "Aktuell",
        max: "Max",
        utilization: "Auslastung",
        noData: "Keine Daten vorhanden.",
        loading: "Wird geladen…",
        backToDashboard: "Zurück zum Dashboard",
      },
    },
    superadmin: {
      title: "Superadmin-Dashboard",
      tabs: {
        overview: "Übersicht",
        users: "Nutzer:innen",
        programmes: "Studiengänge",
        settings: "Einstellungen",
        emailTemplates: "E-Mail-Vorlagen",
      },
      examinerManagement: "Prüferinnen-Verwaltung",
      manageExaminerProfiles: "Verwalten Sie die Profile und Status von Prüfer:innen",
      editProfile: "Profil bearbeiten",
      profileUpdated: "Profil erfolgreich aktualisiert",
      statusUpdated: "Status erfolgreich aktualisiert",
      confirmStatusChange: "Status ändern?",
      statusChangeWarning: "Wenn Sie eine Prüfer:in deaktivieren, kann sie keine neuen Anfragen mehr erhalten.",
      noExaminers: "Keine Prüfer:innen gefunden",
      department: "Abteilung",
      bio: "Biografie",
      researchFocus: "Forschungsschwerpunkt",
      maxSupervisions: "Max. Betreuungen",
      emailTemplates: {
        title: "E-Mail-Vorlagen",
        subtitle: "Bearbeiten Sie die automatisch versendeten E-Mails.",
        edit: "Bearbeiten",
        save: "Speichern",
        cancel: "Abbrechen",
        subject: "Betreff",
        htmlBody: "HTML-Inhalt",
        textBody: "Text-Inhalt (Fallback)",
        preview: "Vorschau",
        placeholders: "Verfügbare Platzhalter",
        saving: "Wird gespeichert…",
        successSave: "Vorlage gespeichert.",
        errorSave: "Fehler beim Speichern.",
        noTemplates: "Keine Vorlagen vorhanden.",
      },
    },
    onboarding: {
      title: "Willkommen bei Thesis Match Maker",
      subtitle: "Bitte vervollständigen Sie Ihr Profil, um Betreuungsanfragen zu erhalten.",
      step1: "Willkommen",
      step2: "Profildaten",
      step3: "Foto",
      step4: "Studiengänge",
      step5: "Kapazität",
      next: "Weiter",
      back: "Zurück",
      finish: "Abschließen",
      skip: "Überspringen",
      academicTitle: "Akademischer Titel",
      department: "Abteilung / Fachbereich",
      bio: "Kurzbeschreibung",
      researchFocus: "Forschungsschwerpunkt",
      officeHours: "Sprechzeiten",
      website: "Website",
      uploadPhoto: "Foto hochladen",
      maxSupervisions: "Maximale Betreuungsanzahl",
      isSecondExaminer: "Als Zweitprüfer:in verfügbar",
      selectProgrammes: "Studiengänge auswählen",
      completing: "Wird abgeschlossen…",
      successComplete: "Profil erfolgreich abgeschlossen!",
    },
    directory: {
      title: "Prüfer:innen-Verzeichnis",
      subtitle: "Alle verfügbaren Prüfer:innen des Fachbereichs 3",
      search: "Name, Fachgebiet oder Studiengang suchen…",
      filterProgramme: "Studiengang",
      filterRole: "Rolle",
      allProgrammes: "Alle Studiengänge",
      allRoles: "Alle Rollen",
      firstExaminer: "Erstprüfer:in",
      secondExaminer: "Zweitprüfer:in",
      noResults: "Keine Prüfer:innen gefunden.",
      capacity: "Kapazität",
      researchFocus: "Forschungsschwerpunkt",
      officeHours: "Sprechzeiten",
      website: "Website",
      requestSupervision: "Betreuung anfragen",
    },
    // Admin Dashboard
    admin: {
      title: "Verwaltungs-Dashboard",
      overview: "Übersicht",
      requests: "Alle Anfragen",
      audit: "Audit-Log",
      users: "Nutzerverwaltung",
      stats: "Statistiken",
      settings: "Einstellungen",
      colloquiums: "Kolloquien",
      totalRequests: "Anfragen gesamt",
      pending: "Ausstehend",
      matched: "Zugeordnet",
      users_count: "Nutzer:innen",
    },
    // Status
    status: {
      PENDING: "Ausstehend",
      ACCEPTED: "Angenommen",
      REJECTED: "Abgelehnt",
      MATCHED: "Zugeordnet",
    },
    // Common
    common: {
      save: "Speichern",
      cancel: "Abbrechen",
      delete: "Löschen",
      edit: "Bearbeiten",
      loading: "Wird geladen…",
      error: "Fehler",
      success: "Erfolgreich",
      confirm: "Bestätigen",
      back: "Zurück",
      search: "Suchen",
      filter: "Filtern",
      all: "Alle",
      noData: "Keine Daten vorhanden.",
      name: "Name",
      email: "E-Mail",
      status: "Status",
      actions: "Aktionen",
      active: "Aktiv",
      inactive: "Inaktiv",
      forbidden: "Zugriff verweigert",
      accessDenied: "Sie haben keinen Zugriff auf diesen Bereich.",
      backHome: "Zur Startseite",
      close: "Schließen",
      errors: {
        networkError: "Netzwerkfehler. Bitte versuchen Sie es später erneut.",
        unauthorized: "Sie sind nicht authentifiziert. Bitte melden Sie sich an.",
        forbidden: "Sie haben keine Berechtigung für diese Aktion.",
        notFound: "Die angeforderte Ressource wurde nicht gefunden.",
        validation: "Bitte überprüfen Sie Ihre Eingaben.",
        serverError: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.",
        invalidEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
        passwordTooShort: "Das Passwort muss mindestens 8 Zeichen lang sein.",
        passwordMismatch: "Die Passwörter stimmen nicht überein.",
        fileTooBig: "Die Datei ist zu groß. Maximum: 16 MB.",
        invalidFileType: "Dieser Dateityp wird nicht unterstützt.",
        duplicateEmail: "Diese E-Mail-Adresse ist bereits registriert.",
      },
      toasts: {
        saved: "Erfolgreich gespeichert!",
        deleted: "Erfolgreich gelöscht!",
        created: "Erfolgreich erstellt!",
        updated: "Erfolgreich aktualisiert!",
        copied: "In die Zwischenablage kopiert!",
        fileUploaded: "Datei erfolgreich hochgeladen!",
        emailSent: "E-Mail erfolgreich versendet!",
        passwordChanged: "Passwort erfolgreich geändert!",
        profileUpdated: "Profil erfolgreich aktualisiert!",
        languageChanged: "Sprache erfolgreich geändert!",
        loggedOut: "Sie wurden erfolgreich abgemeldet.",
      },
    },
  },
  en: {
    // Navigation & Layout
    nav: {
      home: "Home",
      examiners: "Examiners",
      login: "Sign In",
      logout: "Sign Out",
      dashboard: "Dashboard",
      student: "Student",
      examiner: "Examiner",
      admin: "Administration",
      directory: "Examiner Directory",
    },
    // Landing Page
    landing: {
      title: "Thesis Match Maker",
      subtitle: "Find your 2 supervisors with your brilliant academic idea",
      tagline: "The central HTW Berlin platform for thesis supervision matching",
      loginBtn: "Sign In Now",
      loginMagicLink: "Sign in via Magic Link",
      loginManus: "Sign in via HTW Account",
      emailPlaceholder: "Your HTW email address",
      sendLink: "Send Magic Link",
      sending: "Sending…",
      linkSent: "Magic Link sent! Please check your inbox.",
      browseExaminers: "Browse Examiners",
      openArea: "Open area",
      fachbereich: "Department 3",
      heroDesc: "The central HTW Berlin platform for matching students with thesis supervisors – from the first supervision request to the colloquium.",
      startAsStudent: "Start as Student",
      examinerArea: "Examiner Area",
      features: {
        match: "Find Supervisors",
        matchDesc: "Find suitable first and second examiners for your thesis.",
        track: "Track Status",
        trackDesc: "Keep track of requests, deadlines, and colloquiums.",
        secure: "Secure & GDPR-Compliant",
        secureDesc: "All data is processed in accordance with GDPR and stored securely.",
      },
      roles: {
        title: "Who is the platform for?",
        subtitle: "Three roles – one platform",
        student: "Student",
        studentFeatures: ["Submit thesis topic", "Request examiners", "Track status", "Plan colloquium"],
        examiner: "Examiner",
        examinerFeatures: ["Manage requests", "Maintain capacity", "Review templates", "Colloquium calendar"],
        admin: "Administration",
        adminFeatures: ["Admission workflow", "File management", "Audit log"],
      },
      process: {
        label: "The Process",
        title: "From idea to certificate",
        steps: [
          { number: "01", title: "Matchmaking", description: "Submit your topic and contact suitable examiners." },
          { number: "02", title: "Admission", description: "Administration checks prerequisites and grants official admission." },
          { number: "03", title: "Submission", description: "Upload your thesis by 11:59 PM on the submission deadline." },
          { number: "04", title: "Review Phase", description: "First and second examiners write their reviews independently." },
          { number: "05", title: "Colloquium", description: "Schedule finding, room booking, and invitation with calendar attachment." },
          { number: "06", title: "Completion", description: "Minutes, grade sheet, and certificate with digital signature." },
        ],
      },
      tech: {
        label: "Technical Framework",
        title: "Self-hosted. Sovereign. Secure.",
        desc: "The platform runs entirely under",
        descSuffix: "– without external authentication services or US cloud providers.",
        items: [
          { title: "On-Premise Hosting", desc: "Full data sovereignty, no external intermediaries.", icon: "🏗️" },
          { title: "SMTP Authentication", desc: "Login and notifications directly via the HTW mail server.", icon: "✉️" },
          { title: "GDPR-Compliant", desc: "Student phone numbers remain invisible to fellow students.", icon: "🔒" },
          { title: "JWT-Secured CTAs", desc: "Examiners can respond to requests via email link without logging in.", icon: "🔑" },
        ],
      },
      footer: {
        forStudents: "For Students",
        forExaminers: "For Examiners",
        contact: "Contact",
        studentLinks: ["Find examiners", "Submit topic", "Submission portal", "Plan colloquium", "FAQ & Guide"],
        examinerLinks: ["Manage requests", "Maintain availability", "Review templates", "LVVO export", "Committee tools"],
        imprint: "Imprint",
        privacy: "Privacy",
        accessibility: "Accessibility",
        copyright: "© 2026 HTW Berlin",
      },
    },
    // Student Dashboard
    student: {
      title: "Student Dashboard",
      newRequest: "New Request",
      myRequests: "My Requests",
      noRequests: "No requests submitted yet.",
      submitRequest: "Submit Request",
      thesisTitle: "Thesis Title",
      description: "Description",
      department: "Department",
      degreeType: "Degree Type",
      targetSemester: "Target Semester",
      language: "Language",
      uploadExpose: "Upload Exposé (PDF)",
      uploading: "Uploading…",
      uploadSuccess: "Exposé uploaded successfully!",
      deadline: "Submission Deadline",
      downloadIcs: "Download Calendar Event (.ics)",
      colloquiums: "Colloquiums",
      history: "History",
    },
    // Examiner Dashboard
    examiner: {
      title: "Examiner Dashboard",
      requests: "Requests",
      profile: "Profile",
      colloquiums: "Colloquiums",
      history: "History",
      accept: "Accept",
      reject: "Reject",
      downloadExpose: "Download Exposé (PDF)",
      noRequests: "No open requests.",
      programmes: "Study Programmes",
      toastAccepted: "Request accepted!",
      toastRejected: "Request rejected.",
      toastProfileSaved: "Profile saved!",
      toastEmailSaved: "Alternative email saved!",
      toastRoleSaved: "Examiner role saved!",
      toastOnboardingDone: "Profile set up – welcome!",
      statsTotal: "Total",
      statsOpen: "Open",
      statsAccepted: "Accepted",
      statsMatched: "Matched",
      colStatusScheduled: "Scheduled",
      colStatusCompleted: "Completed",
      colStatusCancelled: "Cancelled",
      auditThesisCreated: "Request submitted",
      auditStatusChanged: "Status changed",
      auditExaminerAccepted: "Examiner accepted",
      auditExaminerRejected: "Examiner rejected",
      auditFirstAssigned: "First examiner assigned",
      auditSecondAssigned: "Second examiner assigned",
      auditColloquiumCreated: "Colloquium created",
      auditDeadlineSet: "Deadline set",
    },
    pav: {
      title: "PAV Dashboard",
      unassigned: "Unassigned Students",
      myProgrammes: "My Study Programmes",
      proposeExaminer: "Propose Examiner",
      directAssign: "Direct Assignment",
      sendRequest: "Send Request",
      sending: "Sending…",
      assigning: "Assigning…",
      successPropose: "Request sent successfully.",
      successAssign: "Examiner directly assigned.",
      role: "Role",
      firstExaminer: "First Examiner",
      secondExaminer: "Second Examiner",
      selectExaminer: "Select examiner…",
      selectRole: "Select role…",
      noUnassigned: "No unassigned requests in your study programmes.",
      noProgrammes: "No study programmes assigned yet.",
      addProgramme: "Add",
      removeProgramme: "Remove",
      bachelor: "Bachelor",
      master: "Master",
      proposalNote: "The \"Unassigned Students\" tab will then only show requests from these study programmes.",
    },
    dean: {
      title: "Dean's Dashboard",
      allRequests: "All Requests",
      csvExport: "CSV Export",
      exporting: "Exporting…",
      statistics: "Statistics",
      search: "Title, student, study programme…",
      filterStatus: "Filter by status",
      total: "Total",
      pending: "Pending",
      matched: "Matched",
      accepted: "Accepted",
      rejected: "Rejected",
      dean: "Dean",
      viceDean: "Vice Dean",
      admin: "Admin",
      language_de: "German",
      language_en: "English",
      confirmed: "Confirmed",
      allStatus: "All Statuses",
      searchPlaceholder: "Title, student, study programme…",
      colTopic: "Topic",
      colStudent: "Student",
      colDepartment: "Study Programme",
      colDegree: "Degree",
      colStatus: "Status",
      colSubmitted: "Submitted",
      clickForDetails: "Click on a row to view details.",
      stats: {
        title: "Statistics Dashboard",
        subtitle: "Key metrics and analytics for the dean's office",
        totalRequests: "Total Requests",
        openRequests: "Open Requests",
        avgProcessingTime: "Avg. Processing Time",
        completionRate: "Completion Rate",
        days: "days",
        byStatus: "Requests by Status",
        byProgramme: "Requests by Study Programme",
        byMonth: "Requests per Month (last 12 months)",
        examinerLoad: "Examiner Workload (Top 10)",
        examinerName: "Examiner",
        current: "Current",
        max: "Max",
        utilization: "Utilization",
        noData: "No data available.",
        loading: "Loading…",
        backToDashboard: "Back to Dashboard",
      },
    },
    superadmin: {
      title: "Superadmin Dashboard",
      tabs: {
        overview: "Overview",
        users: "Users",
        programmes: "Study Programmes",
        settings: "Settings",
        emailTemplates: "Email Templates",
      },
      examinerManagement: "Examiner Management",
      manageExaminerProfiles: "Manage examiner profiles and status",
      editProfile: "Edit Profile",
      profileUpdated: "Profile updated successfully",
      statusUpdated: "Status updated successfully",
      confirmStatusChange: "Change Status?",
      statusChangeWarning: "If you deactivate an examiner, they will no longer receive new requests.",
      noExaminers: "No examiners found",
      department: "Department",
      bio: "Biography",
      researchFocus: "Research Focus",
      maxSupervisions: "Max. Supervisions",
      emailTemplates: {
        title: "Email Templates",
        subtitle: "Edit the automatically sent emails.",
        edit: "Edit",
        save: "Save",
        cancel: "Cancel",
        subject: "Subject",
        htmlBody: "HTML Content",
        textBody: "Plain Text (Fallback)",
        preview: "Preview",
        placeholders: "Available Placeholders",
        saving: "Saving…",
        successSave: "Template saved.",
        errorSave: "Error saving template.",
        noTemplates: "No templates available.",
      },
    },
    onboarding: {
      title: "Welcome to Thesis Match Maker",
      subtitle: "Please complete your profile to receive supervision requests.",
      step1: "Welcome",
      step2: "Profile",
      step3: "Photo",
      step4: "Programmes",
      step5: "Capacity",
      next: "Next",
      back: "Back",
      finish: "Complete",
      skip: "Skip",
      academicTitle: "Academic Title",
      department: "Department",
      bio: "Short Description",
      researchFocus: "Research Focus",
      officeHours: "Office Hours",
      website: "Website",
      uploadPhoto: "Upload Photo",
      maxSupervisions: "Maximum Supervisions",
      isSecondExaminer: "Available as Second Examiner",
      selectProgrammes: "Select Study Programmes",
      completing: "Completing…",
      successComplete: "Profile completed successfully!",
    },
    directory: {
      title: "Examiner Directory",
      subtitle: "All available examiners of Department 3",
      search: "Search by name, field, or study programme…",
      filterProgramme: "Study Programme",
      filterRole: "Role",
      allProgrammes: "All Programmes",
      allRoles: "All Roles",
      firstExaminer: "First Examiner",
      secondExaminer: "Second Examiner",
      noResults: "No examiners found.",
      capacity: "Capacity",
      researchFocus: "Research Focus",
      officeHours: "Office Hours",
      website: "Website",
      requestSupervision: "Request Supervision",
    },
    // Admin Dashboard
    admin: {
      title: "Administration Dashboard",
      overview: "Overview",
      requests: "All Requests",
      audit: "Audit Log",
      users: "User Management",
      stats: "Statistics",
      settings: "Settings",
      colloquiums: "Colloquiums",
      totalRequests: "Total Requests",
      pending: "Pending",
      matched: "Matched",
      users_count: "Users",
    },
    // Status
    status: {
      PENDING: "Pending",
      ACCEPTED: "Accepted",
      REJECTED: "Rejected",
      MATCHED: "Matched",
    },
    // Common
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      loading: "Loading…",
      error: "Error",
      success: "Success",
      confirm: "Confirm",
      back: "Back",
      search: "Search",
      filter: "Filter",
      all: "All",
      noData: "No data available.",
      name: "Name",
      email: "Email",
      status: "Status",
      actions: "Actions",
      active: "Active",
      inactive: "Inactive",
      forbidden: "Access Denied",
      accessDenied: "You do not have access to this area.",
      backHome: "Back to Home",
      close: "Close",
      errors: {
        networkError: "Network error. Please try again later.",
        unauthorized: "You are not authenticated. Please sign in.",
        forbidden: "You do not have permission for this action.",
        notFound: "The requested resource was not found.",
        validation: "Please check your input.",
        serverError: "An error occurred. Please try again later.",
        invalidEmail: "Please enter a valid email address.",
        passwordTooShort: "Password must be at least 8 characters long.",
        passwordMismatch: "Passwords do not match.",
        fileTooBig: "File is too large. Maximum: 16 MB.",
        invalidFileType: "This file type is not supported.",
        duplicateEmail: "This email address is already registered.",
      },
      toasts: {
        saved: "Saved successfully!",
        deleted: "Deleted successfully!",
        created: "Created successfully!",
        updated: "Updated successfully!",
        copied: "Copied to clipboard!",
        fileUploaded: "File uploaded successfully!",
        emailSent: "Email sent successfully!",
        passwordChanged: "Password changed successfully!",
        profileUpdated: "Profile updated successfully!",
        languageChanged: "Language changed successfully!",
        loggedOut: "You have been signed out.",
      },
    },
  },
} as const;

export type Translations = typeof translations[Language];

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: typeof translations.de;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    try {
      return (localStorage.getItem("htw-lang") as Language) ?? "de";
    } catch {
      return "de";
    }
  });

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    try {
      localStorage.setItem("htw-lang", newLang);
    } catch {}
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] as typeof translations.de }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

/** Compact language switcher component */
export function LanguageSwitcher({ className = "" }: { className?: string }) {
  const { lang, setLang } = useLanguage();
  
  // Lazy import to avoid circular dependency
  const handleLanguageChange = async (newLang: Language) => {
    setLang(newLang);
    
    // Wenn eingeloggt, Sprache auch in DB speichern
    try {
      const { trpc } = await import("@/lib/trpc");
      const meQuery = trpc.auth.me.useQuery();
      if (meQuery.data) {
        const setLanguageMutation = trpc.auth.setLanguage.useMutation();
        setLanguageMutation.mutate({ language: newLang });
      }
    } catch (error) {
      // Fehler ignorieren wenn nicht eingeloggt oder Hook nicht verfügbar
    }
  };
  
  return (
    <div className={`flex items-center gap-1 ${className}`}>
      <button
        onClick={() => handleLanguageChange("de")}
        className={`px-2 py-1 text-xs font-semibold rounded transition-colors ${
          lang === "de"
            ? "bg-[#76B900] text-white"
            : "text-gray-500 hover:text-gray-800"
        }`}
        aria-label="Deutsch"
      >
        DE
      </button>
      <span className="text-gray-300 text-xs">|</span>
      <button
        onClick={() => handleLanguageChange("en")}
        className={`px-2 py-1 text-xs font-semibold rounded transition-colors ${
          lang === "en"
            ? "bg-[#76B900] text-white"
            : "text-gray-500 hover:text-gray-800"
        }`}
        aria-label="English"
      >
        EN
      </button>
    </div>
  );
}
